import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ChoicePill, EmptyState, Field, PrimaryButton, SecondaryButton, Sheet, StatCard, StatusBadge, colors } from "@/components/app-ui";
import { ScreenContainer } from "@/components/screen-container";
import { calculateBehaviorSummary, getConfiguredPenalty } from "@/lib/behavior";
import { attendanceLabels, behaviorLabels, behaviorViolationLabels, isoToday, noteLabels, useStudentStore, type AttendanceStatus, type BehaviorCategory, type BehaviorViolationType, type NoteCategory } from "@/lib/student-store";
import { buildStudentReport, sharePdf, shareStudentWorkbook } from "@/lib/reporting";
import { formatArabicDate, isolateBidiText } from "@/lib/text-direction";
import { required, validScore } from "@/lib/validation";

type Tab = "grades" | "attendance" | "behavior" | "notes";
const attendanceTone: Record<AttendanceStatus, "green" | "red" | "orange" | "blue"> = { present: "green", absent: "red", excused: "blue", late: "orange", leave: "blue" };
const TAB_LABELS: Record<Tab, string> = { grades: "الدرجات", attendance: "الحضور", behavior: "السلوك", notes: "الملاحظات" };

export default function StudentDetail() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const store = useStudentStore();
  const { data, addGradeField, addGrade, deleteGrade, addBehavior, deleteBehavior, addNote, deleteNote, showSuccess } = store;
  const student = data.students.find((item) => item.id === id);
  const [tab, setTab] = useState<Tab>("grades");
  const [gradeOpen, setGradeOpen] = useState(false);
  const [behaviorOpen, setBehaviorOpen] = useState(false);
  const [noteOpen, setNoteOpen] = useState(false);
  const [gradeForm, setGradeForm] = useState({ subject: "", title: "", score: "", maxScore: "100", term: "الفصل الأول", date: isoToday(), notes: "" });
  const [gradeError, setGradeError] = useState("");
  const [behaviorForm, setBehaviorForm] = useState({ category: "negative" as BehaviorCategory, violationType: "absence" as BehaviorViolationType, title: "", details: "", actionTaken: "", followUp: "", date: isoToday() });
  const [behaviorError, setBehaviorError] = useState("");
  const [noteForm, setNoteForm] = useState({ category: "academic" as NoteCategory, title: "", details: "", needsFollowUp: false, followUpDate: "", date: isoToday() });
  const [noteError, setNoteError] = useState("");

  const attendance = useMemo(() => data.attendance.filter((record) => record.studentId === id).sort((a, b) => b.date.localeCompare(a.date)), [data.attendance, id]);
  const grades = data.grades.filter((record) => record.studentId === id);
  const behaviors = data.behaviors.filter((record) => record.studentId === id);
  const notes = data.notes.filter((record) => record.studentId === id);

  if (!student) return <ScreenContainer><View style={styles.missing}><EmptyState title="الطالب غير موجود" description="قد يكون السجل قد حُذف من هذا الجهاز." icon="person-off" action={<PrimaryButton label="العودة للطلاب" icon="groups" onPress={() => router.back()} />} /></View></ScreenContainer>;

  const className = data.classes.find((item) => item.id === student.classId)?.name ?? "—";
  const sectionName = data.sections.find((item) => item.id === student.sectionId)?.name ?? "—";
  const absent = attendance.filter((item) => item.status === "absent").length;
  const average = grades.length ? Math.round((grades.reduce((sum, grade) => { const field = data.gradeFields.find((item) => item.id === grade.fieldId); return sum + (field ? grade.score / field.maxScore : 0); }, 0) / grades.length) * 100) : 0;
  const behaviorSummary = calculateBehaviorSummary(data, student.id);
  const riskMeta = behaviorSummary.risk === "dismissed" ? { label: "بلغ حد الفصل", tone: "red" as const, icon: "gavel" as const, title: "إشعار فصل" } : behaviorSummary.risk === "warning" ? { label: "يقترب من الحد", tone: "orange" as const, icon: "warning" as const, title: "تنبيه سلوك" } : { label: "سجل سلوكي سليم", tone: "green" as const, icon: "verified" as const, title: "السلوك" };
  const exportPdf = async () => { try { await sharePdf(buildStudentReport(data, student), `ملف_${student.fullName}`); showSuccess("تم إنشاء ملف الطالب PDF بنجاح."); } catch { Alert.alert("تعذر إنشاء PDF", "تحقق من صلاحية مشاركة الملفات وحاول مرة أخرى."); } };
  const exportXlsx = async () => { try { await shareStudentWorkbook(data, student, `بيانات_${student.fullName}`); showSuccess("تم إنشاء ملف الطالب Excel بنجاح."); } catch { Alert.alert("تعذر إنشاء Excel", "تحقق من صلاحية مشاركة الملفات وحاول مرة أخرى."); } };
  const saveGrade = () => {
    const issue = required(gradeForm.subject, "المادة") ?? required(gradeForm.title, "اسم التقييم") ?? validScore(gradeForm.score, gradeForm.maxScore);
    setGradeError(issue ?? ""); if (issue) return;
    const fieldId = addGradeField({ subject: gradeForm.subject, title: gradeForm.title, maxScore: Number(gradeForm.maxScore), term: gradeForm.term, date: gradeForm.date });
    addGrade({ studentId: student.id, fieldId, score: Number(gradeForm.score), notes: gradeForm.notes });
    setGradeForm({ subject: "", title: "", score: "", maxScore: "100", term: "الفصل الأول", date: isoToday(), notes: "" }); setGradeOpen(false);
  };
  const saveBehavior = () => {
    const issue = required(behaviorForm.title, "عنوان السجل") ?? required(behaviorForm.details, "تفاصيل السلوك");
    setBehaviorError(issue ?? ""); if (issue) return;
    const penaltyPoints = behaviorForm.category === "negative" ? getConfiguredPenalty(data, behaviorForm.violationType) : 0;
    addBehavior({ ...behaviorForm, studentId: student.id, penaltyPoints, violationType: behaviorForm.category === "negative" ? behaviorForm.violationType : undefined });
    const nextTotal = behaviorSummary.totalPoints + penaltyPoints;
    const reachedDismissal = behaviorSummary.totalPoints < behaviorSummary.dismissalThreshold && nextTotal >= behaviorSummary.dismissalThreshold;
    setBehaviorForm({ category: "negative", violationType: "absence", title: "", details: "", actionTaken: "", followUp: "", date: isoToday() }); setBehaviorOpen(false);
    if (reachedDismissal) Alert.alert("إشعار فصل الطالب", `بلغ الطالب ${student.fullName} ${nextTotal} نقطة سلوك، وتجاوز حد الفصل المضبوط (${behaviorSummary.dismissalThreshold} نقطة).`);
  };
  const saveNote = () => {
    const issue = required(noteForm.title, "عنوان الملاحظة") ?? required(noteForm.details, "تفاصيل الملاحظة");
    setNoteError(issue ?? ""); if (issue) return;
    addNote({ ...noteForm, studentId: student.id }); setNoteForm({ category: "academic", title: "", details: "", needsFollowUp: false, followUpDate: "", date: isoToday() }); setNoteOpen(false);
  };

  return <ScreenContainer><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">
    <View style={styles.topActions}><Pressable accessibilityRole="button" accessibilityLabel="العودة" onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={22} color={colors.navy} /></Pressable><View style={styles.exports}><SecondaryButton label="Excel" icon="table-view" onPress={exportXlsx} /><SecondaryButton label="PDF" icon="picture-as-pdf" onPress={exportPdf} /></View></View>
    <View style={styles.profile}><View style={styles.largeAvatar}><Text style={styles.largeAvatarText}>{student.firstName.slice(0, 1)}</Text></View><View style={styles.profileText}><View style={styles.nameRow}><Text style={styles.studentName} numberOfLines={2}>{student.fullName}</Text><StatusBadge label={student.status} tone={student.status === "نشط" ? "green" : "orange"} /></View><Text style={styles.profileMeta} numberOfLines={1}>رقم الطالب: {student.studentNumber || "—"}</Text><Text style={styles.profileMeta} numberOfLines={1}>{className} — الشعبة {sectionName}</Text></View></View>
    <View style={[styles.riskCard, behaviorSummary.risk === "dismissed" && styles.riskDismissed, behaviorSummary.risk === "warning" && styles.riskWarning]}><View style={styles.riskIcon}><MaterialIcons name={riskMeta.icon} size={22} color={behaviorSummary.risk === "dismissed" ? colors.danger : behaviorSummary.risk === "warning" ? colors.warning : colors.success} /></View><View style={styles.riskText}><Text style={styles.riskTitle}>{riskMeta.title}</Text><Text style={styles.riskDescription}>{behaviorSummary.risk === "dismissed" ? `تجاوز الطالب حد الفصل: ${behaviorSummary.totalPoints} من ${behaviorSummary.dismissalThreshold} نقطة.` : behaviorSummary.risk === "warning" ? `يتبقى ${behaviorSummary.remainingPoints} نقاط قبل حد الفصل (${behaviorSummary.dismissalThreshold}).` : `إجمالي الخصومات ${behaviorSummary.totalPoints} من ${behaviorSummary.dismissalThreshold} نقطة.`}</Text></View><StatusBadge label={riskMeta.label} tone={riskMeta.tone} /></View>
    <View style={styles.stats}><StatCard label="متوسط الدرجات" value={grades.length ? `${average}%` : "—"} icon="grade" color={colors.blue} /><StatCard label="الغياب" value={absent} icon="event-busy" color={colors.danger} /><StatCard label="نقاط السلوك" value={behaviorSummary.totalPoints} icon="gavel" color={behaviorSummary.risk === "dismissed" ? colors.danger : colors.warning} /></View>
    <View style={styles.tabRow}>{(["grades", "attendance", "behavior", "notes"] as Tab[]).map((item) => <ChoicePill key={item} label={TAB_LABELS[item]} selected={tab === item} onPress={() => setTab(item)} />)}</View>
    {tab === "grades" ? <GradesTab grades={grades} data={data} onAdd={() => setGradeOpen(true)} onDelete={deleteGrade} /> : null}
    {tab === "attendance" ? <AttendanceTab attendance={attendance} /> : null}
    {tab === "behavior" ? <BehaviorTab rows={behaviors} summary={behaviorSummary} onAdd={() => setBehaviorOpen(true)} onDelete={deleteBehavior} /> : null}
    {tab === "notes" ? <NotesTab rows={notes} onAdd={() => setNoteOpen(true)} onDelete={deleteNote} /> : null}
    <View style={styles.guardian}><MaterialIcons name="family-restroom" size={21} color={colors.navy} /><View style={styles.guardianText}><Text style={styles.guardianTitle}>بيانات ولي الأمر</Text><Text style={styles.guardianValue}>{student.guardianName || "لم تُسجل بيانات ولي الأمر"}{student.guardianPhone ? ` · ${student.guardianPhone}` : ""}</Text></View></View>
  </ScrollView>
  <Sheet visible={gradeOpen} title="إضافة درجة" onClose={() => { setGradeOpen(false); setGradeError(""); }}><ScrollView contentContainerStyle={styles.form} keyboardShouldPersistTaps="handled"><Field label="المادة" value={gradeForm.subject} onChangeText={(subject) => setGradeForm({ ...gradeForm, subject })} error={gradeError.includes("المادة") ? gradeError : undefined} placeholder="مثال: الرياضيات" /><Field label="اسم التقييم" value={gradeForm.title} onChangeText={(title) => setGradeForm({ ...gradeForm, title })} error={gradeError.includes("التقييم") ? gradeError : undefined} placeholder="مثال: اختبار الوحدة الأولى" /><View style={styles.twoFields}><View style={styles.fieldHalf}><Field label="الدرجة العظمى" value={gradeForm.maxScore} onChangeText={(maxScore) => setGradeForm({ ...gradeForm, maxScore })} keyboardType="decimal-pad" /></View><View style={styles.fieldHalf}><Field label="درجة الطالب" value={gradeForm.score} onChangeText={(score) => setGradeForm({ ...gradeForm, score })} keyboardType="decimal-pad" error={gradeError && !gradeError.includes("المادة") && !gradeError.includes("التقييم") ? gradeError : undefined} /></View></View><Text style={styles.choiceLabel}>الفصل الدراسي</Text><View style={styles.choices}><ChoicePill label="الفصل الأول" selected={gradeForm.term === "الفصل الأول"} onPress={() => setGradeForm({ ...gradeForm, term: "الفصل الأول" })} /><ChoicePill label="الفصل الثاني" selected={gradeForm.term === "الفصل الثاني"} onPress={() => setGradeForm({ ...gradeForm, term: "الفصل الثاني" })} /></View><Field label="ملاحظات على التقييم" value={gradeForm.notes} onChangeText={(notes) => setGradeForm({ ...gradeForm, notes })} multiline placeholder="اختياري" /><PrimaryButton label="حفظ الدرجة" icon="save" onPress={saveGrade} /></ScrollView></Sheet>
  <Sheet visible={behaviorOpen} title="إضافة سجل سلوك" onClose={() => { setBehaviorOpen(false); setBehaviorError(""); }}><ScrollView contentContainerStyle={styles.form} keyboardShouldPersistTaps="handled"><Text style={styles.choiceLabel}>نوع السجل</Text><View style={styles.choices}>{(["negative", "followup", "positive"] as BehaviorCategory[]).map((item) => <ChoicePill key={item} label={behaviorLabels[item]} selected={behaviorForm.category === item} onPress={() => setBehaviorForm({ ...behaviorForm, category: item })} />)}</View>{behaviorForm.category === "negative" ? <><Text style={styles.choiceLabel}>نوع المخالفة</Text><View style={styles.choices}>{(["absence", "lessonDisruption", "seriousMisconduct", "other"] as BehaviorViolationType[]).map((item) => <ChoicePill key={item} label={behaviorViolationLabels[item]} selected={behaviorForm.violationType === item} onPress={() => setBehaviorForm({ ...behaviorForm, violationType: item })} />)}</View><View style={styles.penaltyPreview}><MaterialIcons name="remove-circle-outline" color={colors.danger} size={20} /><Text style={styles.penaltyPreviewText}>سيُخصم {getConfiguredPenalty(data, behaviorForm.violationType)} نقاط عند حفظ هذه المخالفة.</Text></View></> : null}<Field label="عنوان السجل" value={behaviorForm.title} onChangeText={(title) => setBehaviorForm({ ...behaviorForm, title })} error={behaviorError.includes("عنوان") ? behaviorError : undefined} placeholder="مثال: غياب غير مبرر" /><Field label="تفاصيل السلوك" value={behaviorForm.details} onChangeText={(details) => setBehaviorForm({ ...behaviorForm, details })} multiline error={behaviorError.includes("تفاصيل") ? behaviorError : undefined} placeholder="اكتب وصفًا واضحًا للواقعة أو السلوك" /><Field label="الإجراء المتخذ" value={behaviorForm.actionTaken} onChangeText={(actionTaken) => setBehaviorForm({ ...behaviorForm, actionTaken })} placeholder="اختياري" /><Field label="متابعة لاحقة" value={behaviorForm.followUp} onChangeText={(followUp) => setBehaviorForm({ ...behaviorForm, followUp })} placeholder="اختياري" /><PrimaryButton label="حفظ سجل السلوك" icon="save" onPress={saveBehavior} /></ScrollView></Sheet>
  <Sheet visible={noteOpen} title="إضافة ملاحظة" onClose={() => { setNoteOpen(false); setNoteError(""); }}><ScrollView contentContainerStyle={styles.form} keyboardShouldPersistTaps="handled"><Text style={styles.choiceLabel}>نوع الملاحظة</Text><View style={styles.choices}>{(["academic", "health", "educational", "attendance", "other"] as NoteCategory[]).map((item) => <ChoicePill key={item} label={noteLabels[item]} selected={noteForm.category === item} onPress={() => setNoteForm({ ...noteForm, category: item })} />)}</View><Field label="عنوان الملاحظة" value={noteForm.title} onChangeText={(title) => setNoteForm({ ...noteForm, title })} error={noteError.includes("عنوان") ? noteError : undefined} /><Field label="تفاصيل الملاحظة" value={noteForm.details} onChangeText={(details) => setNoteForm({ ...noteForm, details })} multiline error={noteError.includes("تفاصيل") ? noteError : undefined} /><Text style={styles.choiceLabel}>هل تحتاج متابعة؟</Text><View style={styles.choices}><ChoicePill label="نعم" selected={noteForm.needsFollowUp} onPress={() => setNoteForm({ ...noteForm, needsFollowUp: true })} /><ChoicePill label="لا" selected={!noteForm.needsFollowUp} onPress={() => setNoteForm({ ...noteForm, needsFollowUp: false })} /></View><PrimaryButton label="حفظ الملاحظة" icon="save" onPress={saveNote} /></ScrollView></Sheet>
 </ScreenContainer>;
}

function GradesTab({ grades, data, onAdd, onDelete }: { grades: ReturnType<typeof useStudentStore>["data"]["grades"]; data: ReturnType<typeof useStudentStore>["data"]; onAdd: () => void; onDelete: (id: string) => void }) { return <View style={styles.tabContent}><PrimaryButton label="إضافة تقييم أو درجة" icon="add" onPress={onAdd} />{grades.length ? grades.map((grade) => { const field = data.gradeFields.find((item) => item.id === grade.fieldId); const percent = field ? Math.round((grade.score / field.maxScore) * 100) : 0; return <View key={grade.id} style={styles.record}><Pressable accessibilityRole="button" accessibilityLabel="حذف الدرجة" onPress={() => Alert.alert("حذف الدرجة", "هل تريد حذف هذه الدرجة؟", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => onDelete(grade.id) }])}><MaterialIcons name="delete-outline" size={19} color={colors.danger} /></Pressable><View style={styles.recordText}><Text style={styles.recordTitle} numberOfLines={2}>{field?.subject ?? "مادة"} · {field?.title ?? "تقييم"}</Text><Text style={styles.recordSub} numberOfLines={2}>{grade.score} من {field?.maxScore ?? "—"} · {percent}% · {field?.term}</Text>{grade.notes ? <Text style={styles.recordNote}>{grade.notes}</Text> : null}</View><View style={styles.gradeBadge}><Text style={styles.gradeBadgeText}>{percent}%</Text></View></View>; }) : <EmptyState title="لا توجد درجات بعد" description="أضف حقول تقييم مرنة حسب المادة والاختبار والدرجة العظمى." icon="grade" />}</View>; }
function AttendanceTab({ attendance }: { attendance: ReturnType<typeof useStudentStore>["data"]["attendance"] }) { return <View style={styles.tabContent}>{attendance.length ? attendance.map((record) => <View key={record.id} style={styles.record}><StatusBadge label={attendanceLabels[record.status]} tone={attendanceTone[record.status]} /><View style={styles.recordText}><Text style={styles.recordTitle}>{formatArabicDate(record.date)}</Text><Text style={styles.recordSub} numberOfLines={2}>{record.reason || record.notes || "لا توجد ملاحظات على السجل"}</Text></View><MaterialIcons name="event" size={20} color={colors.blue} /></View>) : <EmptyState title="لا يوجد سجل حضور" description="سجّل الحضور من شاشة الحضور والغياب، وسيظهر تاريخ الطالب هنا." icon="event-note" />}</View>; }
function BehaviorTab({ rows, summary, onAdd, onDelete }: { rows: ReturnType<typeof useStudentStore>["data"]["behaviors"]; summary: ReturnType<typeof calculateBehaviorSummary>; onAdd: () => void; onDelete: (id: string) => void }) { return <View style={styles.tabContent}><View style={styles.behaviorOverview}><Text style={styles.behaviorOverviewValue}>{isolateBidiText(`${summary.totalPoints} / ${summary.dismissalThreshold}`)}</Text><Text style={styles.behaviorOverviewLabel}>نقاط الخصم التراكمية</Text></View><PrimaryButton label="إضافة مخالفة أو سجل" icon="add" onPress={onAdd} />{rows.length ? rows.map((row) => <View key={row.id} style={styles.record}><Pressable accessibilityRole="button" accessibilityLabel="حذف سجل السلوك" onPress={() => Alert.alert("حذف السجل", "هل تريد حذف هذا السجل؟", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => onDelete(row.id) }])}><MaterialIcons name="delete-outline" size={19} color={colors.danger} /></Pressable><View style={styles.recordText}><Text style={styles.recordTitle} numberOfLines={2}>{row.title}</Text><Text style={styles.recordSub} numberOfLines={2}>{formatArabicDate(row.date)} · {row.violationType ? behaviorViolationLabels[row.violationType] : behaviorLabels[row.category]}</Text><Text style={styles.recordNote} numberOfLines={2}>{row.details}</Text></View>{row.category === "negative" ? <View style={styles.pointsBadge}><Text style={styles.pointsBadgeText}>{isolateBidiText(`-${row.penaltyPoints ?? 0}`)}</Text></View> : <StatusBadge label={behaviorLabels[row.category]} tone={row.category === "positive" ? "green" : "orange"} />}</View>) : <EmptyState title="لا توجد سجلات سلوك" description="أضف المخالفات لتطبيق الخصم التراكمي وفق القواعد المحددة في الإعدادات." icon="gavel" />}</View>; }
function NotesTab({ rows, onAdd, onDelete }: { rows: ReturnType<typeof useStudentStore>["data"]["notes"]; onAdd: () => void; onDelete: (id: string) => void }) { return <View style={styles.tabContent}><PrimaryButton label="إضافة ملاحظة" icon="add" onPress={onAdd} />{rows.length ? rows.map((row) => <View key={row.id} style={styles.record}><Pressable accessibilityRole="button" accessibilityLabel="حذف الملاحظة" onPress={() => Alert.alert("حذف الملاحظة", "هل تريد حذف هذه الملاحظة؟", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => onDelete(row.id) }])}><MaterialIcons name="delete-outline" size={19} color={colors.danger} /></Pressable><View style={styles.recordText}><Text style={styles.recordTitle}>{row.title}</Text><Text style={styles.recordSub} numberOfLines={2}>{formatArabicDate(row.date)} · {noteLabels[row.category]}</Text><Text style={styles.recordNote} numberOfLines={2}>{row.details}</Text></View><MaterialIcons name="sticky-note-2" size={20} color={colors.warning} /></View>) : <EmptyState title="لا توجد ملاحظات" description="أضف ملاحظات أكاديمية أو تربوية أو صحية ضمن ملف الطالب." icon="sticky-note-2" />}</View>; }

const styles = StyleSheet.create({
  content: { padding: 16, gap: 14, paddingBottom: 42 }, missing: { flex: 1, justifyContent: "center", padding: 16 }, topActions: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, back: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#E9F1FA", alignItems: "center", justifyContent: "center" }, exports: { flexDirection: "row-reverse", columnGap: 7 },
  profile: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 16, flexDirection: "row-reverse", alignItems: "center", columnGap: 12 }, largeAvatar: { width: 62, height: 62, borderRadius: 31, backgroundColor: colors.navy, alignItems: "center", justifyContent: "center" }, largeAvatarText: { color: colors.white, fontSize: 28, fontWeight: "800" }, profileText: { flex: 1, minWidth: 0, alignItems: "flex-end", rowGap: 3 }, nameRow: { width: "100%", flexDirection: "row-reverse", alignItems: "center", justifyContent: "flex-start", columnGap: 7 }, studentName: { flex: 1, minWidth: 0, color: colors.ink, textAlign: "right", writingDirection: "rtl", fontSize: 19, lineHeight: 27, fontWeight: "800" }, profileMeta: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: "right", writingDirection: "rtl" },
  riskCard: { backgroundColor: "#EAF6EF", borderRadius: 15, padding: 12, flexDirection: "row-reverse", alignItems: "center", columnGap: 9 }, riskDismissed: { backgroundColor: "#FDEAEA" }, riskWarning: { backgroundColor: "#FFF3DE" }, riskIcon: { width: 34, alignItems: "center" }, riskText: { flex: 1, minWidth: 0, alignItems: "flex-end" }, riskTitle: { color: colors.ink, fontSize: 13, fontWeight: "800", textAlign: "right" }, riskDescription: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 2, textAlign: "right" },
  stats: { flexDirection: "row-reverse", columnGap: 8 }, tabRow: { flexDirection: "row-reverse", flexWrap: "wrap", columnGap: 7, rowGap: 7 }, tabContent: { rowGap: 9 },
  record: { minHeight: 68, padding: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, borderRadius: 15, flexDirection: "row-reverse", alignItems: "center", columnGap: 9 }, recordText: { flex: 1, minWidth: 0, alignItems: "flex-end" }, recordTitle: { color: colors.ink, textAlign: "right", writingDirection: "rtl", fontSize: 14, lineHeight: 20, fontWeight: "800" }, recordSub: { color: colors.muted, textAlign: "right", writingDirection: "rtl", fontSize: 12, lineHeight: 18, marginTop: 2 }, recordNote: { color: colors.navy, textAlign: "right", writingDirection: "rtl", fontSize: 11, lineHeight: 17, marginTop: 4 }, gradeBadge: { width: 44, height: 44, borderRadius: 22, backgroundColor: "#E9F1FA", alignItems: "center", justifyContent: "center" }, gradeBadgeText: { color: colors.navy, fontSize: 12, fontWeight: "800" }, pointsBadge: { minWidth: 42, height: 30, paddingHorizontal: 7, borderRadius: 15, backgroundColor: "#FCE2E2", alignItems: "center", justifyContent: "center" }, pointsBadgeText: { color: colors.danger, fontSize: 13, fontWeight: "800" },
  guardian: { padding: 13, columnGap: 9, backgroundColor: "#E9F1FA", borderRadius: 14, flexDirection: "row-reverse", alignItems: "center" }, guardianText: { flex: 1, minWidth: 0, alignItems: "flex-end" }, guardianTitle: { color: colors.navy, fontWeight: "800", fontSize: 13, textAlign: "right" }, guardianValue: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 3, textAlign: "right" },
  form: { paddingBottom: 24 }, twoFields: { flexDirection: "row-reverse", columnGap: 9 }, fieldHalf: { flex: 1, minWidth: 0 }, choiceLabel: { color: colors.ink, textAlign: "right", fontSize: 13, fontWeight: "800", marginBottom: 7 }, choices: { flexDirection: "row-reverse", columnGap: 7, rowGap: 7, flexWrap: "wrap", marginBottom: 14 }, penaltyPreview: { backgroundColor: "#FDEAEA", borderRadius: 12, padding: 11, flexDirection: "row-reverse", alignItems: "center", columnGap: 8, marginTop: -3, marginBottom: 14 }, penaltyPreviewText: { flex: 1, color: colors.danger, fontSize: 12, lineHeight: 18, textAlign: "right", fontWeight: "700" },
  behaviorOverview: { backgroundColor: "#EEF6FF", borderRadius: 15, padding: 13, alignItems: "flex-end" }, behaviorOverviewValue: { color: colors.navy, fontWeight: "800", fontSize: 22, lineHeight: 28 }, behaviorOverviewLabel: { color: colors.muted, fontSize: 12, marginTop: 2 },
});
