import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ChoicePill, EmptyState, Field, PrimaryButton, ScreenHeader, SecondaryButton, Sheet, StatCard, StatusBadge, colors } from "@/components/app-ui";
import { attendanceLabels, behaviorLabels, isoToday, noteLabels, useStudentStore, type AttendanceStatus, type BehaviorCategory, type NoteCategory } from "@/lib/student-store";
import { buildStudentReport, sharePdf, shareStudentWorkbook } from "@/lib/reporting";
import { required, validScore } from "@/lib/validation";
import { ScreenContainer } from "@/components/screen-container";

type Tab = "grades" | "attendance" | "behavior" | "notes";
const attendanceTone: Record<AttendanceStatus, "green" | "red" | "orange" | "blue"> = { present: "green", absent: "red", excused: "blue", late: "orange", leave: "blue" };

export default function StudentDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const store = useStudentStore(); const { data, addGradeField, addGrade, deleteGrade, addBehavior, deleteBehavior, addNote, deleteNote } = store;
  const student = data.students.find((item) => item.id === id); const [tab, setTab] = useState<Tab>("grades"); const [gradeOpen, setGradeOpen] = useState(false); const [behaviorOpen, setBehaviorOpen] = useState(false); const [noteOpen, setNoteOpen] = useState(false);
  const [gradeForm, setGradeForm] = useState({ subject: "", title: "", score: "", maxScore: "100", term: "الفصل الأول", date: isoToday(), notes: "" }); const [gradeError, setGradeError] = useState("");
  const [behaviorForm, setBehaviorForm] = useState({ category: "positive" as BehaviorCategory, title: "", details: "", actionTaken: "", followUp: "", date: isoToday() }); const [behaviorError, setBehaviorError] = useState("");
  const [noteForm, setNoteForm] = useState({ category: "academic" as NoteCategory, title: "", details: "", needsFollowUp: false, followUpDate: "", date: isoToday() }); const [noteError, setNoteError] = useState("");
  const attendance = useMemo(() => data.attendance.filter((record) => record.studentId === id).sort((a, b) => b.date.localeCompare(a.date)), [data.attendance, id]); const grades = data.grades.filter((record) => record.studentId === id); const behaviors = data.behaviors.filter((record) => record.studentId === id); const notes = data.notes.filter((record) => record.studentId === id);
  if (!student) return <ScreenContainer className="p-4"><ScreenHeader title="الطالب غير موجود" /><EmptyState title="تعذر العثور على الطالب" description="قد يكون السجل قد حُذف." icon="person-off" action={<PrimaryButton label="العودة للطلاب" icon="groups" onPress={() => router.back()} />} /></ScreenContainer>;
  const className = data.classes.find((item) => item.id === student.classId)?.name ?? "—"; const sectionName = data.sections.find((item) => item.id === student.sectionId)?.name ?? "—"; const absent = attendance.filter((item) => item.status === "absent").length; const average = grades.length ? Math.round(grades.reduce((sum, grade) => { const field = data.gradeFields.find((item) => item.id === grade.fieldId); return sum + (field ? grade.score / field.maxScore : 0); }, 0) / grades.length * 100) : 0;
  const exportPdf = async () => { try { await sharePdf(buildStudentReport(data, student), `ملف_${student.fullName}`); } catch { Alert.alert("تعذر إنشاء PDF", "حاول مرة أخرى بعد التحقق من صلاحية مشاركة الملفات."); } }; const exportXlsx = async () => { try { await shareStudentWorkbook(data, student, `بيانات_${student.fullName}`); } catch { Alert.alert("تعذر إنشاء Excel", "حاول مرة أخرى بعد التحقق من الصلاحيات."); } };
  const saveGrade = () => { const issue = required(gradeForm.subject, "المادة") ?? required(gradeForm.title, "اسم التقييم") ?? validScore(gradeForm.score, gradeForm.maxScore); setGradeError(issue ?? ""); if (issue) return; const fieldId = addGradeField({ subject: gradeForm.subject, title: gradeForm.title, maxScore: Number(gradeForm.maxScore), term: gradeForm.term, date: gradeForm.date }); addGrade({ studentId: student.id, fieldId, score: Number(gradeForm.score), notes: gradeForm.notes }); setGradeForm({ subject: "", title: "", score: "", maxScore: "100", term: "الفصل الأول", date: isoToday(), notes: "" }); setGradeOpen(false); };
  const saveBehavior = () => { const issue = required(behaviorForm.title, "عنوان السجل") ?? required(behaviorForm.details, "تفاصيل السلوك"); setBehaviorError(issue ?? ""); if (issue) return; addBehavior({ ...behaviorForm, studentId: student.id }); setBehaviorForm({ category: "positive", title: "", details: "", actionTaken: "", followUp: "", date: isoToday() }); setBehaviorOpen(false); };
  const saveNote = () => { const issue = required(noteForm.title, "عنوان الملاحظة") ?? required(noteForm.details, "تفاصيل الملاحظة"); setNoteError(issue ?? ""); if (issue) return; addNote({ ...noteForm, studentId: student.id }); setNoteForm({ category: "academic", title: "", details: "", needsFollowUp: false, followUpDate: "", date: isoToday() }); setNoteOpen(false); };
  return <ScreenContainer className="p-4"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.backRow}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={22} color={colors.navy} /></Pressable><View style={styles.exportButtons}><SecondaryButton label="Excel" icon="table-view" onPress={exportXlsx} /><SecondaryButton label="PDF" icon="picture-as-pdf" onPress={exportPdf} /></View></View>
    <View style={styles.profile}><View style={styles.largeAvatar}><Text style={styles.largeAvatarText}>{student.firstName.slice(0, 1)}</Text></View><View style={styles.profileText}><View style={styles.nameRow}><StatusBadge label={student.status} tone={student.status === "نشط" ? "green" : "orange"} /><Text style={styles.studentName}>{student.fullName}</Text></View><Text style={styles.profileMeta}>رقم الطالب: {student.studentNumber || "—"}</Text><Text style={styles.profileMeta}>{className} — الشعبة {sectionName}</Text></View></View>
    <View style={styles.stats}><StatCard label="متوسط الدرجات" value={grades.length ? `${average}%` : "—"} icon="grade" color={colors.blue} /><StatCard label="الغياب" value={absent} icon="event-busy" color={colors.danger} /><StatCard label="الملاحظات" value={notes.length} icon="sticky-note-2" color={colors.warning} /></View>
    <View style={styles.tabRow}>{(["grades", "attendance", "behavior", "notes"] as Tab[]).map((item) => <ChoicePill key={item} label={{ grades: "الدرجات", attendance: "الحضور", behavior: "السلوك", notes: "الملاحظات" }[item]} selected={tab === item} onPress={() => setTab(item)} />)}</View>
    {tab === "grades" ? <GradesTab grades={grades} data={data} onAdd={() => setGradeOpen(true)} onDelete={deleteGrade} /> : null}{tab === "attendance" ? <AttendanceTab attendance={attendance} /> : null}{tab === "behavior" ? <BehaviorTab rows={behaviors} onAdd={() => setBehaviorOpen(true)} onDelete={deleteBehavior} /> : null}{tab === "notes" ? <NotesTab rows={notes} onAdd={() => setNoteOpen(true)} onDelete={deleteNote} /> : null}
    <View style={styles.guardian}><MaterialIcons name="family-restroom" size={21} color={colors.navy} /><View style={styles.guardianText}><Text style={styles.guardianTitle}>بيانات ولي الأمر</Text><Text style={styles.guardianValue}>{student.guardianName || "لم تُسجل بيانات ولي الأمر"}{student.guardianPhone ? ` · ${student.guardianPhone}` : ""}</Text></View></View>
  </ScrollView>
  <Sheet visible={gradeOpen} title="إضافة درجة" onClose={() => { setGradeOpen(false); setGradeError(""); }}><ScrollView contentContainerStyle={styles.form}><Field label="المادة" value={gradeForm.subject} onChangeText={(subject) => setGradeForm({ ...gradeForm, subject })} error={gradeError.includes("المادة") ? gradeError : undefined} placeholder="مثال: الرياضيات" /><Field label="اسم التقييم" value={gradeForm.title} onChangeText={(title) => setGradeForm({ ...gradeForm, title })} error={gradeError.includes("التقييم") ? gradeError : undefined} placeholder="مثال: اختبار الوحدة الأولى" /><View style={styles.twoFields}><View style={{ flex: 1 }}><Field label="الدرجة العظمى" value={gradeForm.maxScore} onChangeText={(maxScore) => setGradeForm({ ...gradeForm, maxScore })} keyboardType="decimal-pad" /></View><View style={{ flex: 1 }}><Field label="درجة الطالب" value={gradeForm.score} onChangeText={(score) => setGradeForm({ ...gradeForm, score })} keyboardType="decimal-pad" error={gradeError && !gradeError.includes("المادة") && !gradeError.includes("التقييم") ? gradeError : undefined} /></View></View><Text style={styles.choiceLabel}>الفصل الدراسي</Text><View style={styles.choices}><ChoicePill label="الفصل الأول" selected={gradeForm.term === "الفصل الأول"} onPress={() => setGradeForm({ ...gradeForm, term: "الفصل الأول" })} /><ChoicePill label="الفصل الثاني" selected={gradeForm.term === "الفصل الثاني"} onPress={() => setGradeForm({ ...gradeForm, term: "الفصل الثاني" })} /></View><Field label="ملاحظات على التقييم" value={gradeForm.notes} onChangeText={(notes) => setGradeForm({ ...gradeForm, notes })} multiline placeholder="اختياري" /><PrimaryButton label="حفظ الدرجة" icon="save" onPress={saveGrade} /></ScrollView></Sheet>
  <Sheet visible={behaviorOpen} title="إضافة سجل سلوك" onClose={() => { setBehaviorOpen(false); setBehaviorError(""); }}><ScrollView contentContainerStyle={styles.form}><Text style={styles.choiceLabel}>تصنيف السلوك</Text><View style={styles.choices}>{(["positive", "followup", "negative"] as BehaviorCategory[]).map((item) => <ChoicePill key={item} label={behaviorLabels[item]} selected={behaviorForm.category === item} onPress={() => setBehaviorForm({ ...behaviorForm, category: item })} />)}</View><Field label="عنوان السجل" value={behaviorForm.title} onChangeText={(title) => setBehaviorForm({ ...behaviorForm, title })} error={behaviorError.includes("عنوان") ? behaviorError : undefined} placeholder="مثال: مشاركة مميزة" /><Field label="تفاصيل السلوك" value={behaviorForm.details} onChangeText={(details) => setBehaviorForm({ ...behaviorForm, details })} multiline error={behaviorError.includes("تفاصيل") ? behaviorError : undefined} placeholder="اكتب وصفًا واضحًا للواقعة أو السلوك" /><Field label="الإجراء المتخذ" value={behaviorForm.actionTaken} onChangeText={(actionTaken) => setBehaviorForm({ ...behaviorForm, actionTaken })} placeholder="اختياري" /><Field label="متابعة لاحقة" value={behaviorForm.followUp} onChangeText={(followUp) => setBehaviorForm({ ...behaviorForm, followUp })} placeholder="اختياري" /><PrimaryButton label="حفظ السجل" icon="save" onPress={saveBehavior} /></ScrollView></Sheet>
  <Sheet visible={noteOpen} title="إضافة ملاحظة" onClose={() => { setNoteOpen(false); setNoteError(""); }}><ScrollView contentContainerStyle={styles.form}><Text style={styles.choiceLabel}>نوع الملاحظة</Text><View style={styles.choices}>{(["academic", "health", "educational", "attendance", "other"] as NoteCategory[]).map((item) => <ChoicePill key={item} label={noteLabels[item]} selected={noteForm.category === item} onPress={() => setNoteForm({ ...noteForm, category: item })} />)}</View><Field label="عنوان الملاحظة" value={noteForm.title} onChangeText={(title) => setNoteForm({ ...noteForm, title })} error={noteError.includes("عنوان") ? noteError : undefined} /><Field label="تفاصيل الملاحظة" value={noteForm.details} onChangeText={(details) => setNoteForm({ ...noteForm, details })} multiline error={noteError.includes("تفاصيل") ? noteError : undefined} /><Text style={styles.choiceLabel}>هل تحتاج متابعة؟</Text><View style={styles.choices}><ChoicePill label="نعم" selected={noteForm.needsFollowUp} onPress={() => setNoteForm({ ...noteForm, needsFollowUp: true })} /><ChoicePill label="لا" selected={!noteForm.needsFollowUp} onPress={() => setNoteForm({ ...noteForm, needsFollowUp: false })} /></View><PrimaryButton label="حفظ الملاحظة" icon="save" onPress={saveNote} /></ScrollView></Sheet>
 </ScreenContainer>;
}

function GradesTab({ grades, data, onAdd, onDelete }: { grades: ReturnType<typeof useStudentStore>["data"]["grades"]; data: ReturnType<typeof useStudentStore>["data"]; onAdd: () => void; onDelete: (id: string) => void }) { return <View style={styles.tabContent}><PrimaryButton label="إضافة تقييم أو درجة" icon="add" onPress={onAdd} />{grades.length ? grades.map((grade) => { const field = data.gradeFields.find((item) => item.id === grade.fieldId); const percent = field ? Math.round((grade.score / field.maxScore) * 100) : 0; return <View key={grade.id} style={styles.record}><Pressable onPress={() => Alert.alert("حذف الدرجة", "هل تريد حذف هذه الدرجة؟", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => onDelete(grade.id) }])}><MaterialIcons name="delete-outline" size={19} color={colors.danger} /></Pressable><View style={styles.recordText}><Text style={styles.recordTitle}>{field?.subject ?? "مادة"} · {field?.title ?? "تقييم"}</Text><Text style={styles.recordSub}>{grade.score} من {field?.maxScore ?? "—"} · {percent}% · {field?.term}</Text>{grade.notes ? <Text style={styles.recordNote}>{grade.notes}</Text> : null}</View><View style={styles.gradeBadge}><Text style={styles.gradeBadgeText}>{percent}%</Text></View></View>; }) : <EmptyState title="لا توجد درجات بعد" description="أضف حقول تقييم مرنة حسب المادة والاختبار والدرجة العظمى." icon="grade" />}</View>; }
function AttendanceTab({ attendance }: { attendance: ReturnType<typeof useStudentStore>["data"]["attendance"] }) { return <View style={styles.tabContent}>{attendance.length ? attendance.map((record) => <View key={record.id} style={styles.record}><StatusBadge label={attendanceLabels[record.status]} tone={attendanceTone[record.status]} /><View style={styles.recordText}><Text style={styles.recordTitle}>{record.date}</Text><Text style={styles.recordSub}>{record.reason || record.notes || "لا توجد ملاحظات على السجل"}</Text></View><MaterialIcons name="event" size={20} color={colors.blue} /></View>) : <EmptyState title="لا يوجد سجل حضور" description="سجّل الحضور من شاشة الحضور والغياب، وسيظهر تاريخ الطالب هنا." icon="event-note" />}</View>; }
function BehaviorTab({ rows, onAdd, onDelete }: { rows: ReturnType<typeof useStudentStore>["data"]["behaviors"]; onAdd: () => void; onDelete: (id: string) => void }) { return <View style={styles.tabContent}><PrimaryButton label="إضافة سجل سلوك" icon="add" onPress={onAdd} />{rows.length ? rows.map((row) => <View key={row.id} style={styles.record}><Pressable onPress={() => Alert.alert("حذف السجل", "هل تريد حذف هذا السجل؟", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => onDelete(row.id) }])}><MaterialIcons name="delete-outline" size={19} color={colors.danger} /></Pressable><View style={styles.recordText}><Text style={styles.recordTitle}>{row.title}</Text><Text style={styles.recordSub}>{row.date} · {row.details}</Text>{row.actionTaken ? <Text style={styles.recordNote}>الإجراء: {row.actionTaken}</Text> : null}</View><StatusBadge label={behaviorLabels[row.category]} tone={row.category === "positive" ? "green" : row.category === "negative" ? "red" : "orange"} /></View>) : <EmptyState title="لا توجد سجلات سلوك" description="يمكنك تسجيل السلوك الإيجابي أو السلبي وما يحتاج متابعة." icon="psychology" />}</View>; }
function NotesTab({ rows, onAdd, onDelete }: { rows: ReturnType<typeof useStudentStore>["data"]["notes"]; onAdd: () => void; onDelete: (id: string) => void }) { return <View style={styles.tabContent}><PrimaryButton label="إضافة ملاحظة" icon="add" onPress={onAdd} />{rows.length ? rows.map((row) => <View key={row.id} style={styles.record}><Pressable onPress={() => Alert.alert("حذف الملاحظة", "هل تريد حذف هذه الملاحظة؟", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => onDelete(row.id) }])}><MaterialIcons name="delete-outline" size={19} color={colors.danger} /></Pressable><View style={styles.recordText}><Text style={styles.recordTitle}>{row.title}</Text><Text style={styles.recordSub}>{row.date} · {row.details}</Text>{row.needsFollowUp ? <Text style={styles.recordNote}>تحتاج متابعة{row.followUpDate ? `: ${row.followUpDate}` : ""}</Text> : null}</View><StatusBadge label={noteLabels[row.category]} tone="blue" /></View>) : <EmptyState title="لا توجد ملاحظات" description="أضف الملاحظات الأكاديمية أو الصحية أو التربوية الخاصة بالطالب." icon="sticky-note-2" />}</View>; }

const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 30 }, backRow: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, back: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#E9F1FA", alignItems: "center", justifyContent: "center" }, exportButtons: { flexDirection: "row-reverse", gap: 7 }, profile: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 16, flexDirection: "row-reverse", alignItems: "center", gap: 12 }, largeAvatar: { width: 62, height: 62, borderRadius: 31, backgroundColor: colors.navy, alignItems: "center", justifyContent: "center" }, largeAvatarText: { color: colors.white, fontSize: 28, fontWeight: "800" }, profileText: { flex: 1, alignItems: "flex-end", gap: 3 }, nameRow: { flexDirection: "row-reverse", alignItems: "center", gap: 7 }, studentName: { color: colors.ink, fontSize: 19, fontWeight: "800" }, profileMeta: { color: colors.muted, fontSize: 12, textAlign: "right" }, stats: { flexDirection: "row-reverse", gap: 8 }, tabRow: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 7 }, tabContent: { gap: 9 }, record: { minHeight: 66, padding: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, borderRadius: 15, flexDirection: "row-reverse", alignItems: "center", gap: 9 }, recordText: { flex: 1, alignItems: "flex-end" }, recordTitle: { color: colors.ink, textAlign: "right", fontSize: 14, fontWeight: "800" }, recordSub: { color: colors.muted, textAlign: "right", fontSize: 12, lineHeight: 18, marginTop: 2 }, recordNote: { color: colors.navy, textAlign: "right", fontSize: 11, marginTop: 4 }, gradeBadge: { width: 44, height: 44, borderRadius: 22, backgroundColor: "#E9F1FA", alignItems: "center", justifyContent: "center" }, gradeBadgeText: { color: colors.navy, fontSize: 12, fontWeight: "800" }, guardian: { padding: 13, gap: 9, backgroundColor: "#E9F1FA", borderRadius: 14, flexDirection: "row-reverse", alignItems: "center" }, guardianText: { flex: 1, alignItems: "flex-end" }, guardianTitle: { color: colors.navy, fontWeight: "800", fontSize: 13 }, guardianValue: { color: colors.muted, fontSize: 12, marginTop: 3, textAlign: "right" }, form: { paddingBottom: 24 }, twoFields: { flexDirection: "row-reverse", gap: 9 }, choiceLabel: { color: colors.ink, textAlign: "right", fontSize: 13, fontWeight: "800", marginBottom: 7 }, choices: { flexDirection: "row-reverse", gap: 7, flexWrap: "wrap", marginBottom: 14 } });
