import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Alert, FlatList, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ChoicePill, EmptyState, Field, PrimaryButton, ScreenHeader, SecondaryButton, Sheet, colors } from "@/components/app-ui";
import { useStudentStore } from "@/lib/student-store";
import { ScreenContainer } from "@/components/screen-container";
import { required } from "@/lib/validation";

export default function ClassesScreen() { const { data, addClass, addSection, deleteClass, deleteSection } = useStudentStore(); const [classSheet, setClassSheet] = useState(false); const [sectionClassId, setSectionClassId] = useState(""); const [className, setClassName] = useState(""); const [sectionName, setSectionName] = useState(""); const [error, setError] = useState(""); const addClassNow = () => { const issue = required(className, "اسم الصف"); setError(issue ?? ""); if (!issue) { addClass({ name: className.trim(), stage: data.settings.stage, academicYear: data.settings.academicYear }); setClassName(""); setClassSheet(false); } }; const addSectionNow = () => { const issue = required(sectionName, "اسم الشعبة"); setError(issue ?? ""); if (!issue && sectionClassId) { addSection({ classId: sectionClassId, name: sectionName.trim() }); setSectionName(""); setSectionClassId(""); } };
  return <ScreenContainer className="p-4"><ScreenHeader title="الصفوف والشُعب" subtitle="نظّم الطلاب حسب الصف والشعبة" action={<PrimaryButton label="صف" icon="add" onPress={() => setClassSheet(true)} compact />} /><FlatList data={data.classes} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => { const sections = data.sections.filter((section) => section.classId === item.id); const count = data.students.filter((student) => student.classId === item.id).length; return <View style={styles.classCard}><View style={styles.classHead}><View style={styles.classInfo}><Text style={styles.className}>{item.name}</Text><Text style={styles.classMeta}>{sections.length} شعبة · {count} طالبًا</Text></View><View style={styles.classIcon}><MaterialIcons name="class" size={22} color={colors.blue} /></View></View><View style={styles.sectionWrap}>{sections.map((section) => <View style={styles.sectionChip} key={section.id}><Pressable onPress={() => Alert.alert("حذف الشعبة", "سيُحذف طلاب الشعبة وسجلاتهم كذلك.", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => deleteSection(section.id) }])}><MaterialIcons name="close" size={16} color={colors.muted} /></Pressable><Text style={styles.sectionName}>شعبة {section.name}</Text></View>)}<Pressable onPress={() => setSectionClassId(item.id)} style={styles.addSection}><MaterialIcons name="add" size={16} color={colors.navy} /><Text style={styles.addSectionText}>إضافة شعبة</Text></Pressable></View><View style={styles.classActions}><SecondaryButton label="حذف الصف" icon="delete-outline" danger onPress={() => Alert.alert("حذف الصف", "سيُحذف الصف وشُعبه وطلابهم وسجلاتهم نهائيًا.", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => deleteClass(item.id) }])} /></View></View>; }} ListEmptyComponent={<EmptyState title="لم تضف صفوفًا بعد" description="أضف أول صف، مثل الأول، ثم أضف الشُعب مثل أ أو ب." icon="account-tree" action={<PrimaryButton label="إضافة صف" icon="add" onPress={() => setClassSheet(true)} />} />} />
    <Sheet visible={classSheet} title="إضافة صف" onClose={() => { setClassSheet(false); setError(""); }}><Field label="اسم الصف" value={className} onChangeText={setClassName} error={error} placeholder="مثال: الأول" /><Text style={styles.help}>بعد حفظ الصف، أضف له الشُعب مثل: أ، ب، ج.</Text><PrimaryButton label="حفظ الصف" icon="save" onPress={addClassNow} /></Sheet>
    <Sheet visible={Boolean(sectionClassId)} title="إضافة شعبة" onClose={() => { setSectionClassId(""); setError(""); }}><Field label="اسم الشعبة" value={sectionName} onChangeText={setSectionName} error={error} placeholder="مثال: أ" /><PrimaryButton label="حفظ الشعبة" icon="save" onPress={addSectionNow} /></Sheet>
  </ScreenContainer>; }
const styles = StyleSheet.create({ list: { gap: 10, paddingBottom: 35 }, classCard: { backgroundColor: colors.white, borderRadius: 17, borderWidth: 1, borderColor: colors.border, padding: 14, gap: 13 }, classHead: { flexDirection: "row-reverse", alignItems: "center", gap: 10 }, classIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#E9F1FA", alignItems: "center", justifyContent: "center" }, classInfo: { flex: 1, alignItems: "flex-end" }, className: { color: colors.ink, fontSize: 17, fontWeight: "800" }, classMeta: { color: colors.muted, fontSize: 12, marginTop: 3 }, sectionWrap: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 7 }, sectionChip: { backgroundColor: "#F3F7FB", minHeight: 34, paddingHorizontal: 9, borderRadius: 17, flexDirection: "row-reverse", gap: 5, alignItems: "center" }, sectionName: { color: colors.navy, fontSize: 12, fontWeight: "700" }, addSection: { minHeight: 34, borderWidth: 1, borderStyle: "dashed", borderColor: "#AABACB", borderRadius: 17, paddingHorizontal: 9, flexDirection: "row-reverse", gap: 3, alignItems: "center" }, addSectionText: { color: colors.navy, fontSize: 12, fontWeight: "700" }, classActions: { alignItems: "flex-end" }, help: { color: colors.muted, fontSize: 12, textAlign: "right", lineHeight: 19, marginBottom: 14 } });
