import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useMemo, useState } from "react";
import { FlatList, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ChoicePill, EmptyState, PrimaryButton, ScreenHeader, SecondaryButton, Sheet, StatusBadge, colors } from "@/components/app-ui";
import { attendanceLabels, isoToday, useStudentStore, type AttendanceStatus } from "@/lib/student-store";
import { ScreenContainer } from "@/components/screen-container";
import { sortStudentsArabic } from "@/lib/student-order";
import { formatArabicDate, isolateBidiText } from "@/lib/text-direction";

const statuses: AttendanceStatus[] = ["present", "absent", "excused", "late", "leave"];
const tone: Record<AttendanceStatus, "green" | "red" | "orange" | "blue"> = { present: "green", absent: "red", excused: "blue", late: "orange", leave: "blue" };

export default function AttendanceScreen() {
  const { data, saveAttendance } = useStudentStore(); const [classId, setClassId] = useState(""); const [sectionId, setSectionId] = useState(""); const [date, setDate] = useState(isoToday()); const [picker, setPicker] = useState(false); const [values, setValues] = useState<Record<string, AttendanceStatus>>({});
  const students = useMemo(() => sortStudentsArabic(data.students.filter((student) => (!classId || student.classId === classId) && (!sectionId || student.sectionId === sectionId))), [data.students, classId, sectionId]);
  useEffect(() => { const current: Record<string, AttendanceStatus> = {}; students.forEach((student) => { current[student.id] = data.attendance.find((record) => record.studentId === student.id && record.date === date)?.status ?? "present"; }); setValues(current); }, [students, data.attendance, date]);
  const save = () => { saveAttendance(students.map((student) => ({ studentId: student.id, date, status: values[student.id] ?? "present" }))); };
  const classLabel = data.classes.find((item) => item.id === classId)?.name; const sectionLabel = data.sections.find((item) => item.id === sectionId)?.name;
  return <ScreenContainer className="p-4"><ScreenHeader title="الحضور والغياب" subtitle="سجل يومي لكل صف وشعبة" action={<SecondaryButton label="الشُعبة" icon="tune" onPress={() => setPicker(true)} />} />
    <View style={styles.summary}><View style={styles.summaryItem}><Text style={styles.summaryLabel}>التاريخ</Text><Text style={styles.summaryValue}>{formatArabicDate(date)}</Text></View><View style={styles.summaryDivider} /><View style={styles.summaryItem}><Text style={styles.summaryLabel}>الاختيار</Text><Text style={styles.summaryValue}>{sectionLabel ? `${classLabel} — ${sectionLabel}` : classLabel || "اختر صفًا وشعبة"}</Text></View></View>
    <View style={styles.bulk}><SecondaryButton label="تحديد الجميع حاضرًا" icon="done-all" onPress={() => setValues(Object.fromEntries(students.map((student) => [student.id, "present"]))) } /><Text style={styles.counter}>{isolateBidiText(students.length)} طالبًا</Text></View>
    <FlatList data={students} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item, index }) => <AttendanceRow number={index + 1} name={item.fullName} status={values[item.id] ?? "present"} onChange={(status) => setValues({ ...values, [item.id]: status })} />} ListEmptyComponent={<EmptyState title="اختر صفًا وشعبة" description="بعد الاختيار ستظهر قائمة الطلاب لتسجيل حالة حضورهم في هذا التاريخ." icon="fact-check" action={<PrimaryButton label="اختيار الصف والشعبة" icon="tune" onPress={() => setPicker(true)} />} />} />
    {students.length ? <View style={styles.footer}><PrimaryButton label="حفظ سجل الحضور" icon="save" onPress={save} /></View> : null}
    <Sheet visible={picker} title="اختيار الصف والشعبة" onClose={() => setPicker(false)}><ScrollView><Text style={styles.choiceLabel}>الصف</Text><View style={styles.choices}>{data.classes.map((item) => <ChoicePill key={item.id} label={item.name} selected={classId === item.id} onPress={() => { setClassId(item.id); setSectionId(""); }} />)}</View><Text style={styles.choiceLabel}>الشعبة</Text><View style={styles.choices}>{data.sections.filter((item) => item.classId === classId).map((item) => <ChoicePill key={item.id} label={item.name} selected={sectionId === item.id} onPress={() => setSectionId(item.id)} />)}</View><Text style={styles.choiceLabel}>التاريخ</Text><View style={styles.choices}><ChoicePill label="اليوم" selected={date === isoToday()} onPress={() => setDate(isoToday())} /><ChoicePill label="أمس" selected={date !== isoToday()} onPress={() => { const yesterday = new Date(); yesterday.setDate(yesterday.getDate() - 1); setDate(yesterday.toISOString().slice(0, 10)); }} /></View><PrimaryButton label="عرض الطلاب" icon="groups" onPress={() => setPicker(false)} /></ScrollView></Sheet>
  </ScreenContainer>;
}
function AttendanceRow({ number, name, status, onChange }: { number: number; name: string; status: AttendanceStatus; onChange: (status: AttendanceStatus) => void }) { const [open, setOpen] = useState(false); return <View style={styles.attendanceRow}><Pressable onPress={() => setOpen(!open)} style={styles.studentLine}><Text style={styles.attendanceNumber}>{number}</Text><Text style={styles.attendanceName}>{name}</Text><StatusBadge label={attendanceLabels[status]} tone={tone[status]} /><MaterialIcons name={open ? "expand-less" : "expand-more"} size={20} color={colors.muted} /></Pressable>{open ? <View style={styles.statuses}>{statuses.map((item) => <ChoicePill key={item} label={attendanceLabels[item]} selected={status === item} onPress={() => { onChange(item); setOpen(false); }} />)}</View> : null}</View>; }
const styles = StyleSheet.create({ summary: { backgroundColor: "#E9F1FA", borderRadius: 15, padding: 13, flexDirection: "row-reverse", alignItems: "center", gap: 13, marginBottom: 12 }, summaryItem: { flex: 1, minWidth: 0, alignItems: "flex-end" }, summaryLabel: { color: colors.muted, fontSize: 11, textAlign: "right" }, summaryValue: { color: colors.navy, fontSize: 13, fontWeight: "800", marginTop: 3, textAlign: "right" }, summaryDivider: { width: 1, height: 30, backgroundColor: "#C8D8EA" }, bulk: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }, counter: { color: colors.muted, fontSize: 12, textAlign: "right" }, list: { gap: 8, paddingBottom: 92 }, attendanceRow: { backgroundColor: colors.white, borderRadius: 14, borderWidth: 1, borderColor: colors.border, overflow: "hidden" }, studentLine: { minHeight: 58, paddingHorizontal: 13, flexDirection: "row-reverse", alignItems: "center", gap: 9 }, attendanceNumber: { color: colors.navy, fontSize: 13, minWidth: 24, textAlign: "center", fontWeight: "800" }, attendanceName: { flex: 1, color: colors.ink, fontWeight: "800", fontSize: 15, textAlign: "right" }, statuses: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 6, padding: 10, paddingTop: 0, justifyContent: "flex-start" }, footer: { position: "absolute", bottom: 8, left: 16, right: 16, backgroundColor: colors.pale, paddingTop: 7 }, choiceLabel: { color: colors.ink, textAlign: "right", fontSize: 13, fontWeight: "800", marginBottom: 7 }, choices: { flexDirection: "row-reverse", gap: 7, flexWrap: "wrap", marginBottom: 16 } });
