import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useMemo, useState } from "react";
import { EmptyState, PrimaryButton, ScreenHeader, Sheet, StatCard, StatusBadge, colors } from "@/components/app-ui";
import { ScreenContainer } from "@/components/screen-container";
import { calculateBehaviorSummary } from "@/lib/behavior";
import { isoToday, useStudentStore } from "@/lib/student-store";

export default function HomeScreen() {
  const { data, hydrated } = useStudentStore();
  const [alertsOpen, setAlertsOpen] = useState(false);
  const today = isoToday();
  const todayRecords = data.attendance.filter((record) => record.date === today);
  const presentCount = todayRecords.filter((record) => record.status === "present").length;
  const absentCount = todayRecords.filter((record) => record.status === "absent").length;
  const alerts = useMemo(() => data.students.map((student) => ({ student, summary: calculateBehaviorSummary(data, student.id) })).filter((item) => item.summary.risk !== "clear").sort((a, b) => (a.summary.risk === "dismissed" ? -1 : 1) - (b.summary.risk === "dismissed" ? -1 : 1) || b.summary.totalPoints - a.summary.totalPoints), [data]);
  const dismissedCount = alerts.filter((item) => item.summary.risk === "dismissed").length;
  const followUps = data.behaviors.filter((record) => record.category === "followup").slice(0, 3);

  return <ScreenContainer><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <ScreenHeader title={data.settings.schoolName || "سجل الطالب"} subtitle={data.settings.teacherName ? `مرحبًا ${data.settings.teacherName}` : "ابدأ بإضافة المدرسة والمدرس من الإعدادات"} action={<View style={styles.headerActions}><Pressable accessibilityRole="button" accessibilityLabel="تنبيهات السلوك" onPress={() => setAlertsOpen(true)} style={styles.headerButton}><MaterialIcons name="notifications" size={21} color={alerts.length ? colors.danger : colors.navy} />{alerts.length ? <View style={styles.count}><Text style={styles.countText}>{alerts.length > 99 ? "99+" : alerts.length}</Text></View> : null}</Pressable><Pressable accessibilityRole="button" accessibilityLabel="الإعدادات" onPress={() => router.push("/settings" as any)} style={styles.headerButton}><MaterialIcons name="settings" size={21} color={colors.navy} /></Pressable></View>} />
    <View style={styles.stats}><StatCard label="إجمالي الطلاب" value={data.students.length} icon="groups" color={colors.navy} /><StatCard label="حضور اليوم" value={presentCount} icon="check-circle" color={colors.success} /><StatCard label="غياب اليوم" value={absentCount} icon="event-busy" color={colors.danger} /></View>
    {alerts.length ? <Pressable accessibilityRole="button" onPress={() => setAlertsOpen(true)} style={({ pressed }) => [styles.alertBanner, dismissedCount > 0 && styles.alertBannerDanger, pressed && styles.pressed]}><MaterialIcons name={dismissedCount > 0 ? "gavel" : "warning"} size={23} color={dismissedCount > 0 ? colors.danger : colors.warning} /><View style={styles.alertBannerText}><Text style={styles.alertBannerTitle}>{dismissedCount ? `${dismissedCount} طالب بلغ حد الفصل` : `${alerts.length} طالب يقترب من حد الفصل`}</Text><Text style={styles.alertBannerSub}>اضغط لفتح تفاصيل التنبيهات السلوكية.</Text></View><MaterialIcons name="chevron-left" size={21} color={colors.muted} /></Pressable> : null}
    <View style={styles.quickWrap}><PrimaryButton label="تسجيل حضور اليوم" icon="fact-check" onPress={() => router.push("/attendance" as any)} /><PrimaryButton label="إضافة طالب" icon="person-add" onPress={() => router.push("/students?add=1" as any)} /></View>
    <Text style={styles.sectionTitle}>إجراءات سريعة</Text>
    <View style={styles.actions}><QuickAction icon="account-tree" label="الصفوف والشعب" onPress={() => router.push("/classes" as any)} /><QuickAction icon="groups" label="قائمة الطلاب" onPress={() => router.push("/students" as any)} /><QuickAction icon="analytics" label="التقارير" onPress={() => router.push("/reports" as any)} /></View>
    <View style={styles.sectionHead}><Text style={styles.sectionTitle}>متابعة تحتاج انتباهًا</Text><Text style={styles.hint}>آخر السجلات</Text></View>
    {followUps.length ? <View style={styles.followBox}>{followUps.map((item) => { const student = data.students.find((candidate) => candidate.id === item.studentId); return <View style={styles.followRow} key={item.id}><View style={styles.followText}><Text style={styles.followName}>{student?.fullName ?? "طالب محذوف"}</Text><Text style={styles.followDetail} numberOfLines={1}>{item.title}</Text></View><StatusBadge label="متابعة" tone="orange" /></View>; })}</View> : <EmptyState title={hydrated ? "لا توجد تنبيهات متابعة" : "جارٍ تحميل البيانات"} description={hydrated ? "ستظهر هنا السجلات السلوكية التي تحتاج متابعة." : ""} icon="task-alt" />}
    {!data.classes.length ? <View style={styles.startBox}><Text style={styles.startTitle}>خطوة البداية</Text><Text style={styles.startText}>أضف الصفوف والشُعب أولًا، ثم اربط كل طالب بصفه وشعبته.</Text><PrimaryButton label="إدارة الصفوف والشعب" icon="account-tree" onPress={() => router.push("/classes" as any)} /></View> : null}
  </ScrollView>
  <Sheet visible={alertsOpen} title="تنبيهات السلوك والفصل" onClose={() => setAlertsOpen(false)}><ScrollView contentContainerStyle={styles.alertSheet} showsVerticalScrollIndicator={false}>{alerts.length ? alerts.map(({ student, summary }) => <Pressable key={student.id} accessibilityRole="button" onPress={() => { setAlertsOpen(false); router.push(`/student/${student.id}` as any); }} style={({ pressed }) => [styles.alertRow, summary.risk === "dismissed" && styles.alertRowDismissed, pressed && styles.pressed]}><View style={styles.alertRowIcon}><MaterialIcons name={summary.risk === "dismissed" ? "gavel" : "warning"} size={21} color={summary.risk === "dismissed" ? colors.danger : colors.warning} /></View><View style={styles.alertRowText}><Text style={styles.alertRowName} numberOfLines={1}>{student.fullName}</Text><Text style={styles.alertRowDetail} numberOfLines={2}>{summary.risk === "dismissed" ? `مفصول: ${summary.totalPoints} من ${summary.dismissalThreshold} نقطة.` : `تنبيه مبكر: ${summary.totalPoints} من ${summary.dismissalThreshold} نقطة.`}</Text></View><StatusBadge label={summary.risk === "dismissed" ? "فصل" : "تنبيه"} tone={summary.risk === "dismissed" ? "red" : "orange"} /></Pressable>) : <EmptyState title="لا توجد تنبيهات سلوك" description="سيظهر هنا الطلاب الذين يصلون إلى حد التنبيه أو حد الفصل المحدد في الإعدادات." icon="notifications-none" />}</ScrollView></Sheet>
 </ScreenContainer>;
}

function QuickAction({ icon, label, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; label: string; onPress: () => void }) {
  return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.quick, pressed && styles.pressed]}><View style={styles.quickIcon}><MaterialIcons name={icon} size={23} color={colors.blue} /></View><Text style={styles.quickLabel}>{label}</Text><MaterialIcons name="chevron-left" size={20} color="#8B9AAF" /></Pressable>;
}

const styles = StyleSheet.create({
  content: { padding: 16, paddingBottom: 42, rowGap: 16 }, headerActions: { flexDirection: "row-reverse", columnGap: 8 }, headerButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#E9F1FA", alignItems: "center", justifyContent: "center", position: "relative" }, count: { position: "absolute", top: -4, right: -3, minWidth: 18, height: 18, paddingHorizontal: 3, borderRadius: 9, backgroundColor: colors.danger, alignItems: "center", justifyContent: "center" }, countText: { color: colors.white, fontSize: 9, fontWeight: "800" },
  stats: { flexDirection: "row-reverse", columnGap: 8 }, alertBanner: { backgroundColor: "#FFF3DE", borderRadius: 15, padding: 13, flexDirection: "row-reverse", alignItems: "center", columnGap: 10 }, alertBannerDanger: { backgroundColor: "#FDEAEA" }, alertBannerText: { flex: 1, minWidth: 0, alignItems: "flex-end" }, alertBannerTitle: { color: colors.ink, fontWeight: "800", fontSize: 13, textAlign: "right" }, alertBannerSub: { color: colors.muted, fontSize: 11, lineHeight: 17, textAlign: "right", marginTop: 2 },
  quickWrap: { rowGap: 10 }, sectionHead: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", marginTop: 4 }, sectionTitle: { color: colors.ink, fontSize: 17, lineHeight: 24, fontWeight: "800", textAlign: "right" }, hint: { color: colors.muted, fontSize: 12, textAlign: "right" }, actions: { rowGap: 8 }, quick: { minHeight: 62, backgroundColor: colors.white, borderColor: colors.border, borderWidth: 1, borderRadius: 15, paddingHorizontal: 13, flexDirection: "row-reverse", alignItems: "center", columnGap: 11 }, quickIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#EDF5FF", alignItems: "center", justifyContent: "center" }, quickLabel: { flex: 1, minWidth: 0, textAlign: "right", color: colors.ink, fontSize: 16, lineHeight: 23, fontWeight: "800" }, pressed: { opacity: 0.75 },
  followBox: { backgroundColor: colors.white, borderRadius: 15, borderWidth: 1, borderColor: colors.border, overflow: "hidden" }, followRow: { minHeight: 57, paddingHorizontal: 13, flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", columnGap: 12, borderBottomWidth: 1, borderColor: "#EEF2F6" }, followText: { alignItems: "flex-end", flex: 1, minWidth: 0 }, followName: { color: colors.ink, fontSize: 14, fontWeight: "700", textAlign: "right" }, followDetail: { color: colors.muted, fontSize: 12, marginTop: 2, textAlign: "right" }, startBox: { rowGap: 10, backgroundColor: "#E9F1FA", borderRadius: 16, padding: 16, alignItems: "flex-end" }, startTitle: { color: colors.navy, fontWeight: "800", fontSize: 15, textAlign: "right" }, startText: { color: colors.muted, textAlign: "right", lineHeight: 20, fontSize: 13 },
  alertSheet: { rowGap: 9, paddingBottom: 20 }, alertRow: { minHeight: 70, padding: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, borderRadius: 15, flexDirection: "row-reverse", alignItems: "center", columnGap: 10 }, alertRowDismissed: { borderColor: "#E7B6B6", backgroundColor: "#FFF9F9" }, alertRowIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#FDEAEA", alignItems: "center", justifyContent: "center" }, alertRowText: { flex: 1, minWidth: 0, alignItems: "flex-end" }, alertRowName: { color: colors.ink, fontSize: 14, fontWeight: "800", textAlign: "right" }, alertRowDetail: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 2, textAlign: "right" },
});
