import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Alert, ScrollView, StyleSheet, Text, View } from "react-native";
import { EmptyState, PrimaryButton, ScreenHeader, SecondaryButton, colors } from "@/components/app-ui";
import { buildSchoolReport, sharePdf, shareWorkbook } from "@/lib/reporting";
import { useStudentStore } from "@/lib/student-store";
import { ScreenContainer } from "@/components/screen-container";

export default function ReportsScreen() { const { data, showSuccess } = useStudentStore(); const exportPdf = async () => { try { await sharePdf(buildSchoolReport(data), "تقرير المدرسة"); showSuccess("تم إنشاء تقرير PDF بنجاح."); } catch { Alert.alert("تعذر إنشاء التقرير", "تحقق من صلاحية مشاركة الملفات وحاول مرة أخرى."); } }; const exportExcel = async () => { try { await shareWorkbook(data, "بيانات_المدرسة"); showSuccess("تم إنشاء ملف Excel بنجاح."); } catch { Alert.alert("تعذر إنشاء ملف Excel", "حاول مرة أخرى بعد إضافة بعض البيانات."); } };
  return <ScreenContainer className="p-4"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><ScreenHeader title="التقارير والتصدير" subtitle="ملفات منظمة قابلة للطباعة والمشاركة" />
    <View style={styles.hero}><View style={styles.heroIcon}><MaterialIcons name="description" size={29} color={colors.white} /></View><Text style={styles.heroTitle}>تقرير المدرسة العام</Text><Text style={styles.heroText}>يشمل كشف الطلاب وإجماليات اليوم، ويستخدم اسم المدرسة والمدرس في رأس التقرير.</Text><View style={styles.heroButtons}><PrimaryButton label="PDF بحجم A4" icon="picture-as-pdf" onPress={exportPdf} /><SecondaryButton label="Excel" icon="table-view" onPress={exportExcel} /></View></View>
    <Text style={styles.sectionTitle}>ماذا يتضمن التصدير؟</Text><View style={styles.rows}><ReportRow icon="groups" title="كشف الطلاب" text={`${data.students.length} طالبًا مع الصف والشعبة والحالة.`} /><ReportRow icon="fact-check" title="الحضور والغياب" text={`${data.attendance.length} سجل حضور محفوظ.`} /><ReportRow icon="grade" title="الدرجات" text={`${data.grades.length} درجة مسجلة ضمن حقول تقييم مرنة.`} /></View>
    {!data.students.length ? <EmptyState title="التقرير بانتظار البيانات" description="أضف الصفوف والشعب والطلاب أولًا لتنتج تقارير مفيدة." icon="analytics" /> : null}
    <View style={styles.note}><MaterialIcons name="info-outline" size={19} color={colors.navy} /><Text style={styles.noteText}>يمكنك تصدير ملف الطالب المفصل مباشرةً من داخل ملفه الشخصي، أما هذه الشاشة فتنتج تقرير المدرسة العام وملف Excel متعدد الأوراق.</Text></View>
  </ScrollView></ScreenContainer>; }
function ReportRow({ icon, title, text }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; text: string }) { return <View style={styles.reportRow}><View style={styles.rowIcon}><MaterialIcons name={icon} size={21} color={colors.blue} /></View><View style={styles.rowText}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowSub}>{text}</Text></View></View>; }
const styles = StyleSheet.create({ content: { gap: 18, paddingBottom: 48 }, hero: { backgroundColor: colors.navy, borderRadius: 22, padding: 20, alignItems: "flex-end", gap: 10 }, heroIcon: { width: 48, height: 48, borderRadius: 24, backgroundColor: "#2F80ED", alignItems: "center", justifyContent: "center" }, heroTitle: { color: colors.white, fontSize: 21, lineHeight: 29, fontWeight: "800", textAlign: "right" }, heroText: { color: "#D4E3F4", fontSize: 15, lineHeight: 23, textAlign: "right" }, heroButtons: { flexDirection: "row-reverse", gap: 10, width: "100%" }, sectionTitle: { color: colors.ink, fontSize: 18, lineHeight: 26, fontWeight: "800", textAlign: "right", marginTop: 6 }, rows: { backgroundColor: colors.white, borderRadius: 18, borderWidth: 1, borderColor: colors.border, overflow: "hidden" }, reportRow: { minHeight: 74, paddingHorizontal: 16, flexDirection: "row-reverse", alignItems: "center", gap: 12, borderBottomWidth: 1, borderBottomColor: "#EEF2F6" }, rowIcon: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: "#E9F1FA" }, rowText: { flex: 1, alignItems: "flex-end" }, rowTitle: { color: colors.ink, fontSize: 16, lineHeight: 22, fontWeight: "800", textAlign: "right" }, rowSub: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 3, textAlign: "right" }, note: { borderRadius: 16, backgroundColor: "#E9F1FA", padding: 16, flexDirection: "row-reverse", alignItems: "flex-start", gap: 10 }, noteText: { flex: 1, color: colors.navy, textAlign: "right", fontSize: 14, lineHeight: 22 } });
