import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Alert, ScrollView, StyleSheet, Text, View } from "react-native";
import { Field, PrimaryButton, ScreenHeader, SecondaryButton, colors } from "@/components/app-ui";
import { useStudentStore } from "@/lib/student-store";
import { ScreenContainer } from "@/components/screen-container";
import { required } from "@/lib/validation";
import { useState } from "react";

export default function SettingsScreen() { const { data, updateSettings, resetAll } = useStudentStore(); const [form, setForm] = useState(data.settings); const [error, setError] = useState(""); const save = () => { const issue = required(form.schoolName, "اسم المدرسة") ?? required(form.teacherName, "اسم المدرس"); setError(issue ?? ""); if (!issue) updateSettings(form); }; return <ScreenContainer className="p-4"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><ScreenHeader title="إعدادات المدرسة" subtitle="تظهر هذه البيانات في رأس التطبيق والتقارير" />
  <View style={styles.card}><View style={styles.cardHead}><View style={styles.icon}><MaterialIcons name="school" color={colors.blue} size={23} /></View><Text style={styles.cardTitle}>هوية المدرسة</Text></View><Field label="اسم المدرسة" value={form.schoolName} onChangeText={(schoolName) => setForm({ ...form, schoolName })} error={error.includes("المدرسة") ? error : undefined} placeholder="مثال: مدرسة النور الأساسية" /><Field label="اسم المدرس" value={form.teacherName} onChangeText={(teacherName) => setForm({ ...form, teacherName })} error={error.includes("المدرس") ? error : undefined} placeholder="الاسم الثلاثي" /><Field label="العام الدراسي" value={form.academicYear} onChangeText={(academicYear) => setForm({ ...form, academicYear })} placeholder="2026 / 2027" /><Field label="المرحلة التعليمية" value={form.stage} onChangeText={(stage) => setForm({ ...form, stage })} placeholder="مثال: المرحلة الابتدائية" /><PrimaryButton label="حفظ الإعدادات" icon="save" onPress={save} /></View>
  <View style={styles.card}><View style={styles.cardHead}><View style={[styles.icon, { backgroundColor: "#FDE8E7" }]}><MaterialIcons name="delete-sweep" color={colors.danger} size={23} /></View><Text style={styles.cardTitle}>إدارة البيانات</Text></View><Text style={styles.warning}>سيؤدي الحذف إلى إزالة جميع الصفوف والطلاب والسجلات من هذا الجهاز، ولا يمكن التراجع عنه.</Text><SecondaryButton label="حذف جميع البيانات" icon="delete-forever" danger onPress={() => Alert.alert("حذف جميع البيانات", "هل أنت متأكد؟ لا يمكن استرجاع الصفوف والطلاب والسجلات بعد الحذف.", [{ text: "إلغاء", style: "cancel" }, { text: "حذف نهائي", style: "destructive", onPress: resetAll }])} /></View>
  <Text style={styles.privacy}>يُحفظ سجل التطبيق محليًا على هذا الجهاز. استخدم تصدير Excel أو PDF للاحتفاظ بنسخ من التقارير عند الحاجة.</Text>
</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { gap: 15, paddingBottom: 30 }, card: { backgroundColor: colors.white, borderRadius: 17, borderWidth: 1, borderColor: colors.border, padding: 15 }, cardHead: { flexDirection: "row-reverse", alignItems: "center", gap: 10, marginBottom: 15 }, icon: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#E9F1FA", alignItems: "center", justifyContent: "center" }, cardTitle: { color: colors.ink, fontSize: 16, fontWeight: "800" }, warning: { color: colors.muted, textAlign: "right", fontSize: 13, lineHeight: 20, marginBottom: 13 }, privacy: { color: colors.muted, fontSize: 12, lineHeight: 19, textAlign: "center", paddingHorizontal: 12 } });
