import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { FlatList, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ChoicePill, EmptyState, Field, PrimaryButton, ScreenHeader, SecondaryButton, Sheet, colors } from "@/components/app-ui";
import { ScreenContainer } from "@/components/screen-container";
import { calculateBehaviorSummary } from "@/lib/behavior";
import { attentionFilterLabel, countStudentAbsences, filterStudentsByAttention, REPEATED_ABSENCE_THRESHOLD, type StudentAttentionFilter } from "@/lib/student-attention-filter";
import { sortStudentsArabic } from "@/lib/student-order";
import { useStudentStore, type Student } from "@/lib/student-store";
import { required, validPhone } from "@/lib/validation";

type Form = { studentNumber: string; firstName: string; fatherName: string; lastName: string; gender: "ذكر" | "أنثى"; classId: string; sectionId: string; guardianName: string; guardianPhone: string };
const emptyForm: Form = { studentNumber: "", firstName: "", fatherName: "", lastName: "", gender: "ذكر", classId: "", sectionId: "", guardianName: "", guardianPhone: "" };

export default function StudentsScreen() {
  const { data, addStudent } = useStudentStore();
  const params = useLocalSearchParams<{ add?: string }>();
  const [mode, setMode] = useState<"table" | "sections">("sections");
  const [query, setQuery] = useState(""); const [classId, setClassId] = useState(""); const [sectionId, setSectionId] = useState("");
  const [attentionFilter, setAttentionFilter] = useState<StudentAttentionFilter>("all");
  const [filterOpen, setFilterOpen] = useState(false); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState<Form>(emptyForm); const [errors, setErrors] = useState<Record<string, string>>({});
  useEffect(() => { if (params.add === "1") setFormOpen(true); }, [params.add]);
  const filtered = useMemo(() => {
    const scopedStudents = data.students.filter((student) => (!classId || student.classId === classId) && (!sectionId || student.sectionId === sectionId) && (!query || `${student.fullName} ${student.studentNumber}`.includes(query.trim())));
    return sortStudentsArabic(filterStudentsByAttention(data, scopedStudents, attentionFilter));
  }, [data, classId, sectionId, query, attentionFilter]);
  const classLabel = data.classes.find((item) => item.id === classId)?.name; const sectionLabel = data.sections.find((item) => item.id === sectionId)?.name;
  const activeScopeLabel = [sectionLabel ? `${classLabel} — ${sectionLabel}` : classLabel || "كل الصفوف", attentionFilter !== "all" ? attentionFilterLabel(attentionFilter) : ""].filter(Boolean).join(" · ");
  const groups = data.sections.filter((section) => (!classId || section.classId === classId) && (!sectionId || section.id === sectionId)).map((section) => ({ section, students: filtered.filter((student) => student.sectionId === section.id) }));
  const save = () => {
    const next = { firstName: required(form.firstName, "الاسم الأول"), lastName: required(form.lastName, "اسم العائلة"), classId: required(form.classId, "الصف"), sectionId: required(form.sectionId, "الشعبة"), guardianPhone: validPhone(form.guardianPhone) };
    const active = Object.fromEntries(Object.entries(next).filter(([, value]) => value)) as Record<string, string>; setErrors(active); if (Object.keys(active).length) return;
    const id = addStudent({ ...form, status: "نشط" }); setForm(emptyForm); setFormOpen(false); router.push(`/student/${id}` as any);
  };

  return <ScreenContainer className="p-4"><ScreenHeader title="الطلاب" subtitle={`${data.students.length} طالبًا مسجلًا`} action={<PrimaryButton label="إضافة" icon="person-add" onPress={() => setFormOpen(true)} compact />} />
    <View style={styles.importAction}><SecondaryButton label="استيراد الطلاب من ملف" icon="file-upload" onPress={() => router.push("/import-students" as any)} /></View>
    <View style={styles.searchRow}><Pressable accessibilityRole="button" accessibilityLabel="تصفية الطلاب" onPress={() => setFilterOpen(true)} style={styles.filter}><MaterialIcons name="tune" color={colors.navy} size={21} /></Pressable><View style={styles.search}><MaterialIcons name="search" color={colors.muted} size={20} /><TextInput value={query} onChangeText={setQuery} placeholder="ابحث بالاسم أو الرقم" placeholderTextColor="#96A4B8" textAlign="right" style={styles.searchInput} /></View></View>
    <View style={styles.modeRow}><View style={styles.modeChoices}><ChoicePill label="قائمة الشُعب" selected={mode === "sections"} onPress={() => setMode("sections")} /><ChoicePill label="عرض جدولي" selected={mode === "table"} onPress={() => setMode("table")} /></View><Text style={styles.filterText}>{activeScopeLabel}</Text></View>
    {mode === "table" ? filtered.length ? <StudentTable students={filtered} /> : <View style={styles.list}><EmptyState title="لا توجد نتائج" description="غيّر التصفية أو البحث، أو أضف طالبًا جديدًا." icon="group-off" action={<PrimaryButton label="إضافة طالب" icon="person-add" onPress={() => setFormOpen(true)} />} /></View> : <FlatList data={groups} keyExtractor={(item) => item.section.id} contentContainerStyle={styles.list} renderItem={({ item }) => <SectionGroup name={`${data.classes.find((klass) => klass.id === item.section.classId)?.name ?? ""} — الشعبة ${item.section.name}`} students={item.students} startIndex={filtered.findIndex((student) => student.id === item.students[0]?.id)} />} ListEmptyComponent={<EmptyState title="لا توجد شُعب أو طلاب" description="غيّر التصفية أو أضف الصف والشعبة ثم أسماء الطلاب." icon="group-add" action={<PrimaryButton label="إدارة الصفوف" icon="account-tree" onPress={() => router.push("/classes" as any)} />} />} />}
    <Sheet visible={filterOpen} title="تصفية الطلاب" onClose={() => setFilterOpen(false)}><ScrollView showsVerticalScrollIndicator={false}><Text style={styles.sheetHint}>اختر الصف والشعبة، أو حالة المتابعة التي تريد عرضها.</Text><Text style={styles.choiceLabel}>الصف</Text><View style={styles.choices}><ChoicePill label="الكل" selected={!classId} onPress={() => { setClassId(""); setSectionId(""); }} />{data.classes.map((item) => <ChoicePill key={item.id} label={item.name} selected={classId === item.id} onPress={() => { setClassId(item.id); setSectionId(""); }} />)}</View><Text style={styles.choiceLabel}>الشعبة</Text><View style={styles.choices}><ChoicePill label="الكل" selected={!sectionId} onPress={() => setSectionId("")} />{data.sections.filter((item) => !classId || item.classId === classId).map((item) => <ChoicePill key={item.id} label={item.name} selected={sectionId === item.id} onPress={() => setSectionId(item.id)} />)}</View><Text style={styles.choiceLabel}>حالة المتابعة</Text><View style={styles.choices}><ChoicePill label="كل الطلاب" selected={attentionFilter === "all"} onPress={() => setAttentionFilter("all")} /><ChoicePill label="تنبيه سلوكي" selected={attentionFilter === "behavior-alert"} onPress={() => setAttentionFilter("behavior-alert")} /><ChoicePill label={`غيابات متكررة (${REPEATED_ABSENCE_THRESHOLD}+)`} selected={attentionFilter === "repeated-absence"} onPress={() => setAttentionFilter("repeated-absence")} /></View><View style={styles.filterActions}><SecondaryButton label="إعادة الضبط" icon="restart-alt" onPress={() => { setClassId(""); setSectionId(""); setAttentionFilter("all"); }} /><PrimaryButton label="تطبيق التصفية" icon="check" onPress={() => setFilterOpen(false)} /></View></ScrollView></Sheet>
    <StudentForm visible={formOpen} onClose={() => { setFormOpen(false); setErrors({}); }} data={data} form={form} setForm={setForm} errors={errors} onSave={save} />
  </ScreenContainer>;
}

function StudentSummary({ item, index }: { item: Student; index: number }) {
  const { data } = useStudentStore(); const behavior = calculateBehaviorSummary(data, item.id); const absences = countStudentAbsences(data, item.id);
  return <View style={styles.studentInfo}><View style={styles.nameLine}><Text style={styles.studentNumber}>{index + 1}</Text><Text style={styles.studentName} numberOfLines={1}>{item.fullName}</Text></View><View style={styles.factRow}><Text style={[styles.fact, behavior.risk === "dismissed" && styles.dangerFact]}>السلوك: {behavior.totalPoints} نقطة</Text><Text style={styles.fact}>الغيابات: {absences}</Text></View></View>;
}

function StudentCard({ item, index }: { item: Student; index: number }) { return <Pressable accessibilityRole="button" onPress={() => router.push(`/student/${item.id}` as any)} style={({ pressed }) => [styles.studentCard, pressed && styles.pressed]}><MaterialIcons name="chevron-left" size={22} color="#92A0B2" /><StudentSummary item={item} index={index} /><View style={styles.avatar}><Text style={styles.avatarText}>{item.firstName.slice(0, 1)}</Text></View></Pressable>; }

function StudentTable({ students }: { students: Student[] }) {
  const { data } = useStudentStore();
  return <ScrollView horizontal showsHorizontalScrollIndicator contentContainerStyle={styles.tableScroll} style={styles.tableViewport}><View style={styles.table}><View style={[styles.tableRow, styles.tableHeader]}><Text style={[styles.tableCell, styles.cellIndex, styles.tableHeaderText]}>ت</Text><Text style={[styles.tableCell, styles.cellName, styles.tableHeaderText]}>الاسم الكامل</Text><Text style={[styles.tableCell, styles.cellBehavior, styles.tableHeaderText]}>السلوك</Text><Text style={[styles.tableCell, styles.cellAbsence, styles.tableHeaderText]}>الغيابات</Text></View>{students.map((item, index) => { const behavior = calculateBehaviorSummary(data, item.id); const absences = countStudentAbsences(data, item.id); return <Pressable key={item.id} accessibilityRole="button" onPress={() => router.push(`/student/${item.id}` as any)} style={({ pressed }) => [styles.tableRow, pressed && styles.pressed]}><Text style={[styles.tableCell, styles.cellIndex]}>{index + 1}</Text><Text style={[styles.tableCell, styles.cellName]} numberOfLines={1}>{item.fullName}</Text><Text style={[styles.tableCell, styles.cellBehavior, behavior.risk === "dismissed" && styles.dismissedText]}>{behavior.totalPoints} نقطة</Text><Text style={[styles.tableCell, styles.cellAbsence]}>{absences}</Text></Pressable>; })}</View></ScrollView>;
}

function SectionGroup({ name, students, startIndex }: { name: string; students: Student[]; startIndex: number }) { const [open, setOpen] = useState(true); return <View style={styles.group}><Pressable accessibilityRole="button" onPress={() => setOpen(!open)} style={styles.groupHead}><View style={styles.groupName}><Text style={styles.groupTitle}>{name}</Text><Text style={styles.groupCount}>{students.length} طالبًا</Text></View><MaterialIcons name={open ? "expand-less" : "expand-more"} size={22} color={colors.navy} /></Pressable>{open ? students.length ? <View style={styles.groupList}>{students.map((student, index) => <StudentCard item={student} index={startIndex + index} key={student.id} />)}</View> : <Text style={styles.noStudents}>لا يوجد طلاب مسجلون في هذه الشعبة.</Text> : null}</View>; }

function StudentForm({ visible, onClose, data, form, setForm, errors, onSave }: { visible: boolean; onClose: () => void; data: ReturnType<typeof useStudentStore>["data"]; form: Form; setForm: (form: Form) => void; errors: Record<string, string>; onSave: () => void }) { const sections = data.sections.filter((item) => item.classId === form.classId); const set = (key: keyof Form, value: string) => setForm({ ...form, [key]: value, ...(key === "classId" ? { sectionId: "" } : {}) }); return <Sheet visible={visible} title="إضافة طالب" onClose={onClose}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.formContent}><Field label="رقم الطالب" value={form.studentNumber} onChangeText={(value) => set("studentNumber", value)} keyboardType="numeric" placeholder="اختياري" /><Field label="الاسم الأول" value={form.firstName} onChangeText={(value) => set("firstName", value)} error={errors.firstName} /><Field label="اسم الأب" value={form.fatherName} onChangeText={(value) => set("fatherName", value)} placeholder="اختياري" /><Field label="اسم العائلة" value={form.lastName} onChangeText={(value) => set("lastName", value)} error={errors.lastName} /><Text style={styles.choiceLabel}>الجنس</Text><View style={styles.choices}><ChoicePill label="ذكر" selected={form.gender === "ذكر"} onPress={() => set("gender", "ذكر")} /><ChoicePill label="أنثى" selected={form.gender === "أنثى"} onPress={() => set("gender", "أنثى")} /></View><Text style={styles.choiceLabel}>الصف</Text><View style={styles.choices}>{data.classes.map((item) => <ChoicePill key={item.id} label={item.name} selected={form.classId === item.id} onPress={() => set("classId", item.id)} />)}</View>{errors.classId ? <Text style={styles.formError}>{errors.classId}</Text> : null}<Text style={styles.choiceLabel}>الشعبة</Text><View style={styles.choices}>{sections.map((item) => <ChoicePill key={item.id} label={item.name} selected={form.sectionId === item.id} onPress={() => set("sectionId", item.id)} />)}</View>{errors.sectionId ? <Text style={styles.formError}>{errors.sectionId}</Text> : null}<Field label="اسم ولي الأمر" value={form.guardianName} onChangeText={(value) => set("guardianName", value)} placeholder="اختياري" /><Field label="هاتف ولي الأمر" value={form.guardianPhone} onChangeText={(value) => set("guardianPhone", value)} keyboardType="phone-pad" error={errors.guardianPhone} placeholder="اختياري" /><PrimaryButton label="حفظ الطالب" icon="save" onPress={onSave} disabled={!data.classes.length || !data.sections.length} /></ScrollView></Sheet>; }

const styles = StyleSheet.create({
  importAction: { alignItems: "flex-end", marginBottom: 12 }, searchRow: { flexDirection: "row-reverse", gap: 9, marginBottom: 12 }, filter: { width: 48, height: 48, borderRadius: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, alignItems: "center", justifyContent: "center" }, search: { flex: 1, flexDirection: "row-reverse", alignItems: "center", gap: 8, backgroundColor: colors.white, borderColor: colors.border, borderWidth: 1, borderRadius: 14, paddingHorizontal: 14 }, searchInput: { flex: 1, minHeight: 46, color: colors.ink, writingDirection: "rtl", textAlign: "right", fontSize: 16 },
  modeRow: { flexDirection: "row-reverse", alignItems: "center", gap: 8, marginBottom: 14 }, modeChoices: { flexDirection: "row-reverse", gap: 8 }, filterText: { flex: 1, color: colors.muted, textAlign: "right", fontSize: 14, lineHeight: 20 }, filterActions: { flexDirection: "row-reverse", gap: 10, marginTop: 16 }, list: { gap: 10, paddingBottom: 112 },
  studentCard: { minHeight: 82, borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, paddingHorizontal: 14, flexDirection: "row-reverse", alignItems: "center", gap: 12 }, avatar: { width: 46, height: 46, borderRadius: 23, backgroundColor: "#E9F1FA", alignItems: "center", justifyContent: "center" }, avatarText: { color: colors.navy, fontSize: 18, fontWeight: "800" }, studentInfo: { flex: 1, minWidth: 0, alignItems: "flex-end", gap: 6 }, nameLine: { width: "100%", flexDirection: "row-reverse", gap: 9, alignItems: "center" }, studentNumber: { color: colors.navy, backgroundColor: colors.blueSurface, borderRadius: 12, overflow: "hidden", minWidth: 28, paddingVertical: 3, paddingHorizontal: 6, fontSize: 13, lineHeight: 18, fontWeight: "800", textAlign: "center" }, studentName: { flex: 1, minWidth: 0, color: colors.ink, fontSize: 17, lineHeight: 24, fontWeight: "800", textAlign: "right" }, factRow: { width: "100%", flexDirection: "row-reverse", gap: 13 }, fact: { color: colors.muted, fontSize: 13, lineHeight: 19, textAlign: "right" }, dangerFact: { color: colors.danger, fontWeight: "800" }, pressed: { opacity: 0.72 },
  group: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: 18, overflow: "hidden" }, groupHead: { minHeight: 66, paddingHorizontal: 15, flexDirection: "row-reverse", alignItems: "center", gap: 10, backgroundColor: "#F9FBFD" }, groupName: { flex: 1, alignItems: "flex-end" }, groupTitle: { color: colors.ink, fontSize: 17, lineHeight: 24, fontWeight: "800", textAlign: "right" }, groupCount: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 3, textAlign: "right" }, groupList: { gap: 0 }, noStudents: { color: colors.muted, padding: 16, textAlign: "right", fontSize: 15, lineHeight: 22 },
  tableViewport: { maxHeight: "100%" }, tableScroll: { paddingBottom: 112, direction: "rtl" as never }, table: { minWidth: 515, borderWidth: 1, borderColor: colors.border, borderRadius: 16, overflow: "hidden", backgroundColor: colors.white }, tableRow: { minHeight: 58, flexDirection: "row-reverse", alignItems: "center", borderBottomWidth: 1, borderBottomColor: "#E7EDF4" }, tableHeader: { minHeight: 48, backgroundColor: "#E9F1FA" }, tableCell: { color: colors.ink, fontSize: 14, lineHeight: 20, paddingHorizontal: 10, textAlign: "right" }, tableHeaderText: { color: colors.navy, fontSize: 13, fontWeight: "800" }, cellIndex: { width: 45, textAlign: "center" }, cellName: { width: 220, fontWeight: "700" }, cellBehavior: { width: 140 }, cellAbsence: { width: 110, textAlign: "center" }, dismissedText: { color: colors.danger, fontWeight: "800" },
  sheetHint: { color: colors.muted, fontSize: 15, lineHeight: 22, textAlign: "right", marginBottom: 12 }, choiceLabel: { color: colors.ink, textAlign: "right", fontSize: 15, fontWeight: "800", marginBottom: 8 }, choices: { flexDirection: "row-reverse", flexWrap: "wrap", justifyContent: "flex-start", gap: 8, marginBottom: 16 }, formContent: { paddingBottom: 22 }, formError: { color: colors.danger, textAlign: "right", fontSize: 14, lineHeight: 20, marginTop: -9, marginBottom: 13 },
});
