import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { FlatList, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ChoicePill, EmptyState, Field, PrimaryButton, ScreenHeader, Sheet, StatusBadge, colors } from "@/components/app-ui";
import { calculateBehaviorSummary } from "@/lib/behavior";
import { useStudentStore, type Student } from "@/lib/student-store";
import { required, validPhone } from "@/lib/validation";
import { ScreenContainer } from "@/components/screen-container";

type Form = { studentNumber: string; firstName: string; fatherName: string; lastName: string; gender: "ذكر" | "أنثى"; classId: string; sectionId: string; guardianName: string; guardianPhone: string };
const emptyForm: Form = { studentNumber: "", firstName: "", fatherName: "", lastName: "", gender: "ذكر", classId: "", sectionId: "", guardianName: "", guardianPhone: "" };

export default function StudentsScreen() {
  const { data, addStudent } = useStudentStore();
  const params = useLocalSearchParams<{ add?: string }>();
  const [mode, setMode] = useState<"table" | "sections">("sections");
  const [query, setQuery] = useState(""); const [classId, setClassId] = useState(""); const [sectionId, setSectionId] = useState("");
  const [filterOpen, setFilterOpen] = useState(false); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState<Form>(emptyForm); const [errors, setErrors] = useState<Record<string, string>>({});
  useEffect(() => { if (params.add === "1") setFormOpen(true); }, [params.add]);
  const filtered = useMemo(() => data.students.filter((student) => (!classId || student.classId === classId) && (!sectionId || student.sectionId === sectionId) && (!query || `${student.fullName} ${student.studentNumber}`.includes(query.trim()))), [data.students, classId, sectionId, query]);
  const classLabel = data.classes.find((item) => item.id === classId)?.name; const sectionLabel = data.sections.find((item) => item.id === sectionId)?.name;
  const save = () => {
    const next = { firstName: required(form.firstName, "الاسم الأول"), lastName: required(form.lastName, "اسم العائلة"), classId: required(form.classId, "الصف"), sectionId: required(form.sectionId, "الشعبة"), guardianPhone: validPhone(form.guardianPhone) };
    const active = Object.fromEntries(Object.entries(next).filter(([, value]) => value)) as Record<string, string>; setErrors(active); if (Object.keys(active).length) return;
    const id = addStudent({ ...form, status: "نشط" }); setForm(emptyForm); setFormOpen(false); router.push(`/student/${id}` as any);
  };
  const groups = data.sections.filter((section) => (!classId || section.classId === classId) && (!sectionId || section.id === sectionId)).map((section) => ({ section, students: filtered.filter((student) => student.sectionId === section.id) }));

  return <ScreenContainer className="p-4"><ScreenHeader title="الطلاب" subtitle={`${data.students.length} طالبًا مسجلًا`} action={<PrimaryButton label="إضافة" icon="person-add" onPress={() => setFormOpen(true)} compact />} />
    <View style={styles.searchRow}><Pressable onPress={() => setFilterOpen(true)} style={styles.filter}><MaterialIcons name="tune" color={colors.navy} size={21} /></Pressable><View style={styles.search}><MaterialIcons name="search" color={colors.muted} size={20} /><TextInput value={query} onChangeText={setQuery} placeholder="ابحث بالاسم أو الرقم" placeholderTextColor="#96A4B8" textAlign="right" style={styles.searchInput} /></View></View>
    <View style={styles.modeRow}><ChoicePill label="قائمة الشُعب" selected={mode === "sections"} onPress={() => setMode("sections")} /><ChoicePill label="عرض جدولي" selected={mode === "table"} onPress={() => setMode("table")} /><Text style={styles.filterText}>{sectionLabel ? `${classLabel} — ${sectionLabel}` : classLabel || "كل الصفوف"}</Text></View>
    {mode === "table" ? <FlatList data={filtered} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <StudentCard item={item} />} ListEmptyComponent={<EmptyState title="لا توجد نتائج" description="غيّر البحث أو أضف طالبًا جديدًا." icon="group-off" action={<PrimaryButton label="إضافة طالب" icon="person-add" onPress={() => setFormOpen(true)} />} />} /> : <FlatList data={groups} keyExtractor={(item) => item.section.id} contentContainerStyle={styles.list} renderItem={({ item }) => <SectionGroup name={`${data.classes.find((klass) => klass.id === item.section.classId)?.name ?? ""} — الشعبة ${item.section.name}`} students={item.students} />} ListEmptyComponent={<EmptyState title="لا توجد شُعب أو طلاب" description="ابدأ بإضافة الصف والشعبة ثم أسماء الطلاب." icon="group-add" action={<PrimaryButton label="إدارة الصفوف" icon="account-tree" onPress={() => router.push("/classes" as any)} />} />} />}
    <Sheet visible={filterOpen} title="تصفية الطلاب" onClose={() => setFilterOpen(false)}><ScrollView showsVerticalScrollIndicator={false}><Text style={styles.sheetHint}>اختر الصف، ثم الشعبة إن لزم الأمر.</Text><Text style={styles.choiceLabel}>الصف</Text><View style={styles.choices}><ChoicePill label="الكل" selected={!classId} onPress={() => { setClassId(""); setSectionId(""); }} />{data.classes.map((item) => <ChoicePill key={item.id} label={item.name} selected={classId === item.id} onPress={() => { setClassId(item.id); setSectionId(""); }} />)}</View><Text style={styles.choiceLabel}>الشعبة</Text><View style={styles.choices}><ChoicePill label="الكل" selected={!sectionId} onPress={() => setSectionId("")} />{data.sections.filter((item) => !classId || item.classId === classId).map((item) => <ChoicePill key={item.id} label={item.name} selected={sectionId === item.id} onPress={() => setSectionId(item.id)} />)}</View><PrimaryButton label="تطبيق التصفية" icon="check" onPress={() => setFilterOpen(false)} /></ScrollView></Sheet>
    <StudentForm visible={formOpen} onClose={() => { setFormOpen(false); setErrors({}); }} data={data} form={form} setForm={setForm} errors={errors} onSave={save} />
  </ScreenContainer>;
}

function StudentCard({ item }: { item: Student }) { const { data } = useStudentStore(); const className = data.classes.find((klass) => klass.id === item.classId)?.name ?? "—"; const section = data.sections.find((candidate) => candidate.id === item.sectionId)?.name ?? "—"; const behavior = calculateBehaviorSummary(data, item.id); const behaviorLabel = behavior.risk === "dismissed" ? "مفصول" : behavior.risk === "warning" ? "تنبيه سلوك" : null; return <Pressable onPress={() => router.push(`/student/${item.id}` as any)} style={({ pressed }) => [styles.studentCard, behavior.risk === "dismissed" && styles.dismissedCard, pressed && styles.pressed]}><View style={styles.avatar}><Text style={styles.avatarText}>{item.firstName.slice(0, 1)}</Text></View><View style={styles.studentInfo}><View style={styles.nameLine}><Text style={styles.studentName} numberOfLines={1}>{item.fullName}</Text>{behaviorLabel ? <StatusBadge label={behaviorLabel} tone={behavior.risk === "dismissed" ? "red" : "orange"} /> : <StatusBadge label={item.status} tone={item.status === "نشط" ? "green" : "orange"} />}</View><Text style={styles.studentMeta} numberOfLines={1}>#{item.studentNumber || "—"} · {className} / {section}</Text>{behavior.risk !== "clear" ? <Text style={styles.behaviorMeta}>السلوك: {behavior.totalPoints} / {behavior.dismissalThreshold} نقطة</Text> : null}</View><MaterialIcons name="chevron-left" size={22} color="#92A0B2" /></Pressable>; }
function SectionGroup({ name, students }: { name: string; students: Student[] }) { const [open, setOpen] = useState(true); return <View style={styles.group}><Pressable onPress={() => setOpen(!open)} style={styles.groupHead}><MaterialIcons name={open ? "expand-less" : "expand-more"} size={22} color={colors.navy} /><View style={styles.groupName}><Text style={styles.groupTitle}>{name}</Text><Text style={styles.groupCount}>{students.length} طالبًا</Text></View></Pressable>{open ? students.length ? <View style={styles.groupList}>{students.map((student) => <StudentCard item={student} key={student.id} />)}</View> : <Text style={styles.noStudents}>لا يوجد طلاب مسجلون في هذه الشعبة.</Text> : null}</View>; }
function StudentForm({ visible, onClose, data, form, setForm, errors, onSave }: { visible: boolean; onClose: () => void; data: ReturnType<typeof useStudentStore>["data"]; form: Form; setForm: (form: Form) => void; errors: Record<string, string>; onSave: () => void }) { const sections = data.sections.filter((item) => item.classId === form.classId); const set = (key: keyof Form, value: string) => setForm({ ...form, [key]: value, ...(key === "classId" ? { sectionId: "" } : {}) }); return <Sheet visible={visible} title="إضافة طالب" onClose={onClose}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.formContent}><Field label="رقم الطالب" value={form.studentNumber} onChangeText={(value) => set("studentNumber", value)} keyboardType="numeric" placeholder="اختياري" /><Field label="الاسم الأول" value={form.firstName} onChangeText={(value) => set("firstName", value)} error={errors.firstName} /><Field label="اسم الأب" value={form.fatherName} onChangeText={(value) => set("fatherName", value)} placeholder="اختياري" /><Field label="اسم العائلة" value={form.lastName} onChangeText={(value) => set("lastName", value)} error={errors.lastName} /><Text style={styles.choiceLabel}>الجنس</Text><View style={styles.choices}><ChoicePill label="ذكر" selected={form.gender === "ذكر"} onPress={() => set("gender", "ذكر")} /><ChoicePill label="أنثى" selected={form.gender === "أنثى"} onPress={() => set("gender", "أنثى")} /></View><Text style={styles.choiceLabel}>الصف</Text><View style={styles.choices}>{data.classes.map((item) => <ChoicePill key={item.id} label={item.name} selected={form.classId === item.id} onPress={() => set("classId", item.id)} />)}</View>{errors.classId ? <Text style={styles.formError}>{errors.classId}</Text> : null}<Text style={styles.choiceLabel}>الشعبة</Text><View style={styles.choices}>{sections.map((item) => <ChoicePill key={item.id} label={item.name} selected={form.sectionId === item.id} onPress={() => set("sectionId", item.id)} />)}</View>{errors.sectionId ? <Text style={styles.formError}>{errors.sectionId}</Text> : null}<Field label="اسم ولي الأمر" value={form.guardianName} onChangeText={(value) => set("guardianName", value)} placeholder="اختياري" /><Field label="هاتف ولي الأمر" value={form.guardianPhone} onChangeText={(value) => set("guardianPhone", value)} keyboardType="phone-pad" error={errors.guardianPhone} placeholder="اختياري" /><PrimaryButton label="حفظ الطالب" icon="save" onPress={onSave} disabled={!data.classes.length || !data.sections.length} /></ScrollView></Sheet>; }

const styles = StyleSheet.create({ searchRow: { flexDirection: "row", gap: 9, marginBottom: 10 }, filter: { width: 46, height: 46, borderRadius: 13, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, alignItems: "center", justifyContent: "center" }, search: { flex: 1, flexDirection: "row", alignItems: "center", gap: 7, backgroundColor: colors.white, borderColor: colors.border, borderWidth: 1, borderRadius: 13, paddingHorizontal: 12 }, searchInput: { flex: 1, minHeight: 44, color: colors.ink, writingDirection: "rtl", textAlign: "right" }, modeRow: { flexDirection: "row", alignItems: "center", gap: 7, marginBottom: 12 }, filterText: { flex: 1, color: colors.muted, textAlign: "right", fontSize: 11 }, list: { gap: 9, paddingBottom: 100 }, studentCard: { minHeight: 70, borderRadius: 15, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 10 }, dismissedCard: { borderColor: "#E7B6B6", backgroundColor: "#FFF9F9" }, avatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#E9F1FA", alignItems: "center", justifyContent: "center" }, avatarText: { color: colors.navy, fontSize: 17, fontWeight: "800" }, studentInfo: { flex: 1, minWidth: 0, alignItems: "flex-end", gap: 4 }, nameLine: { width: "100%", flexDirection: "row", gap: 7, alignItems: "center" }, studentName: { flex: 1, minWidth: 0, color: colors.ink, fontSize: 15, fontWeight: "800", textAlign: "right" }, studentMeta: { color: colors.muted, fontSize: 12, textAlign: "right" }, behaviorMeta: { color: colors.danger, fontSize: 11, textAlign: "right", fontWeight: "700" }, pressed: { opacity: 0.72 }, group: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: 16, overflow: "hidden" }, groupHead: { minHeight: 56, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 9, backgroundColor: "#F9FBFD" }, groupName: { flex: 1, alignItems: "flex-end" }, groupTitle: { color: colors.ink, fontSize: 15, fontWeight: "800" }, groupCount: { color: colors.muted, fontSize: 11, marginTop: 2 }, groupList: { gap: 0 }, noStudents: { color: colors.muted, padding: 14, textAlign: "right", fontSize: 12 }, sheetHint: { color: colors.muted, textAlign: "right", fontSize: 13, marginBottom: 15 }, choiceLabel: { color: colors.ink, textAlign: "right", fontSize: 13, fontWeight: "800", marginTop: 4, marginBottom: 7 }, choices: { flexDirection: "row", gap: 7, flexWrap: "wrap", marginBottom: 13 }, formContent: { paddingBottom: 28 }, formError: { color: colors.danger, textAlign: "right", fontSize: 11, marginTop: -6, marginBottom: 8 } });
